# Copyright (C) 2026, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""BITS-style bi-level imitation behavior model."""

from .config import BitsConfig
from .cache import (
    BITS_BATCH_CACHE_VERSION,
    build_bits_batch_cache,
    build_bits_batch_cache_parallel,
    iter_bits_batch_cache,
    load_bits_batch,
    load_bits_batch_cache,
    load_bits_batch_cache_manifest,
    rebuild_bits_batch_cache_manifest,
    save_bits_batch,
)
from .dataset import BitsBatchBuilder, BitsSampleDataset, BitsSampleIndex, NuPlanBitsDataset
from .evaluation import (
    BitsRollingEvaluation,
    evaluate_bits_rolling_result,
)
from .model import (
    BitsAgentPrediction,
    BitsBehaviorModel,
    BitsPlan,
    BitsPlanScoreBreakdown,
    BitsPlanScorer,
    BitsPolicy,
    BitsPrediction,
)
from .rasterizer import BitsRasterizer
from .rolling import BitsRollingResult, BitsRollingRunner
from .schema import BitsBatch, BitsRaster
from .supervision import (
    BitsGoalSupervision,
    build_goal_supervision,
)
from .training import (
    BitsCheckpointMetadata,
    BitsInferenceLoadResult,
    BitsProtocolResult,
    BitsRunConfig,
    BitsTrainingHistory,
    BitsTrainingSchedule,
    NuPlanBitsSplit,
    NuPlanLogSpec,
    OFFICIAL_TBSIM_BITS_CHECKPOINTS,
    bits_run_config_from_dict,
    bits_run_config_to_dict,
    build_nuplan_bits_dataset,
    evaluate_nuplan_bits_planner_split,
    evaluate_nuplan_bits_split,
    infer_image_channels,
    iter_nuplan_bits_batches,
    load_bits_checkpoint,
    load_bits_run_config,
    load_bits_inference_model,
    load_tbsim_bits_inference_weights,
    map_tbsim_bits_planner_state_dict,
    map_tbsim_bits_predictor_state_dict,
    merge_tbsim_bits_state_dicts,
    run_nuplan_bits_torch_validation,
    run_nuplan_bits_open_loop_protocol,
    run_nuplan_bits_planner_protocol,
    run_nuplan_bits_rolling_protocol,
    save_bits_checkpoint,
    save_bits_run_config,
    train_nuplan_bits_planner,
    train_nuplan_bits_model,
)

__all__ = [
    "BitsBatch",
    "BitsBatchBuilder",
    "BitsAgentPrediction",
    "BitsBehaviorModel",
    "BITS_BATCH_CACHE_VERSION",
    "BitsConfig",
    "BitsCheckpointMetadata",
    "BitsInferenceLoadResult",
    "BitsProtocolResult",
    "BitsPlan",
    "BitsPlanScoreBreakdown",
    "BitsPlanScorer",
    "BitsPolicy",
    "BitsPrediction",
    "BitsRaster",
    "BitsRasterizer",
    "BitsRollingEvaluation",
    "BitsRollingResult",
    "BitsRollingRunner",
    "BitsRunConfig",
    "BitsSampleDataset",
    "BitsSampleIndex",
    "BitsTrainingHistory",
    "BitsTrainingSchedule",
    "BitsGoalSupervision",
    "NuPlanBitsDataset",
    "NuPlanBitsSplit",
    "NuPlanLogSpec",
    "OFFICIAL_TBSIM_BITS_CHECKPOINTS",
    "bits_run_config_from_dict",
    "bits_run_config_to_dict",
    "build_bits_batch_cache",
    "build_bits_batch_cache_parallel",
    "build_goal_supervision",
    "build_nuplan_bits_dataset",
    "evaluate_nuplan_bits_planner_split",
    "evaluate_nuplan_bits_split",
    "evaluate_bits_rolling_result",
    "infer_image_channels",
    "iter_nuplan_bits_batches",
    "iter_bits_batch_cache",
    "load_bits_batch",
    "load_bits_batch_cache",
    "load_bits_batch_cache_manifest",
    "rebuild_bits_batch_cache_manifest",
    "load_bits_checkpoint",
    "load_bits_run_config",
    "load_bits_inference_model",
    "load_tbsim_bits_inference_weights",
    "map_tbsim_bits_planner_state_dict",
    "map_tbsim_bits_predictor_state_dict",
    "merge_tbsim_bits_state_dicts",
    "run_nuplan_bits_torch_validation",
    "run_nuplan_bits_open_loop_protocol",
    "run_nuplan_bits_planner_protocol",
    "run_nuplan_bits_rolling_protocol",
    "save_bits_checkpoint",
    "save_bits_batch",
    "save_bits_run_config",
    "train_nuplan_bits_planner",
    "train_nuplan_bits_model",
]
