# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    exclude: tactics2d/participant/trajectory_classifier.m
  - id: end-of-file-fixer
    exclude: tactics2d/participant/trajectory_classifier.m
  - id: check-toml
  - id: check-yaml
  - id: check-added-large-files
    args: [--maxkb=50000]
  - id: requirements-txt-fixer
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args: [--profile=black]
- repo: https://github.com/python/black
  rev: 25.1.0
  hooks:
  - id: black
    args: ["--line-length", "100", "--color", "--skip-magic-trailing-comma"]
- repo: https://github.com/cpp-linter/cpp-linter-hooks
  rev: v0.8.0  # Use the ref you want to point at
  hooks:
    - id: clang-format
      args: []
# -   repo: https://github.com/pre-commit/mirrors-eslint
#     rev: 'v9.27.0'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: eslint
