# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
    exclude: tactics2d/participant/trajectory_classifier.m
  - id: end-of-file-fixer
    exclude: tactics2d/participant/trajectory_classifier.m
  - id: check-toml
  - id: check-yaml
  - id: check-added-large-files
    args: [--maxkb=5000]
  - id: requirements-txt-fixer
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.1
  hooks:
  - id: pyupgrade
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [--profile=black]
- repo: https://github.com/python/black
  rev: 24.3.0
  hooks:
  - id: black
    args: ["--line-length", "100", "--color"]
- repo: https://github.com/cpp-linter/cpp-linter-hooks
  rev: v0.6.1  # Use the ref you want to point at
  hooks:
    - id: clang-format
      args: []
