# Copyright (C) 2026, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""Render configuration implementation.

Merged from the previous ``matplotlib_config.py`` and ``render_template.py``.
"""


COLOR_PALETTE = {
    "red": "#fc5c65",
    "light-red": "#fc5c65",
    "orange": "#fa8231",
    "light-orange": "#fd9644",
    "yellow": "#f7b731",
    "light-yellow": "#fed330",
    "green": "#20bf6b",
    "light-green": "#26de81",
    "turquoise": "#0fb9b1",
    "light-turquoise": "#2bcbba",
    "blue": "#2d98da",
    "light-blue": "#45aaf2",
    "royal-blue": "#3867d6",
    "light-royal-blue": "#4b7bec",
    "purple": "#8854d0",
    "light-purple": "#a55eea",
    "pink": "#fc5c8d",
    "light-pink": "#ff9ff3",
    "white": "#f1f2f6",
    "light-gray": "#a5b1c2",
    "gray": "#b2bec3",
    "dark-gray": "#4b6584",
    "black": "#2f3542",
}

DEFAULT_COLOR = {
    # default color for lane class subtypes
    "lane": "black",
    "slipLane": "black",
    "road": "black",
    "driving": "black",
    "bidirectional": "black",
    "highway": "black",
    "play_street": "gray",
    "emergency_lane": "red",
    "bus_lane": "dark-gray",
    "bus": "dark-gray",
    "bicycle_lane": "dark-gray",
    "biking": "dark-gray",
    "offRamp": "dark-gray",
    "onRamp": "dark-gray",
    "entry": "green",
    "exit": "green",
    "sidewalk": "gray",
    "walking": "gray",
    "walkway": "gray",
    "shared_walkway": "gray",
    "crosswalk": "dark-gray",
    "stairs": "gray",
    # default color for junction class subtypes
    # matches SUMO-GUI's default grey intersection fill
    "junction": "dark-gray",
    "priority": "dark-gray",
    "traffic_light": "dark-gray",
    "right_before_left": "dark-gray",
    "unregulated": "dark-gray",
    "dead_end": "dark-gray",
    "rail_signal": "dark-gray",
    "zipper": "dark-gray",
    "rail_crossing": "dark-gray",
    "allway_stop": "dark-gray",
    # default color for area class subtypes
    "area": "black",
    "hole": "white",
    "parking": "black",
    "parkingSpace": "black",
    "rail": "dark-gray",
    "freespace": "black",
    "vegetation": "green",
    "keepout": "red",
    "stop": "red",
    "building": "gray",
    "grass": "green",
    "water": "blue",
    "wood": "green",
    # area subtypes from standard OSM tags
    "commercial": "gray",
    "retail": "gray",
    "industrial": "gray",
    "shelter": "gray",
    "swimming_pool": "blue",
    "park": "green",
    "traffic_island": "dark-gray",
    "obstacle": "gray",
    # road types from standard OSM highway tags
    "motorway": "dark-gray",
    "motorway_link": "dark-gray",
    "trunk": "dark-gray",
    "trunk_link": "dark-gray",
    "primary": "dark-gray",
    "primary_link": "dark-gray",
    "secondary": "dark-gray",
    "secondary_link": "dark-gray",
    "tertiary": "dark-gray",
    "tertiary_link": "dark-gray",
    "residential": "dark-gray",
    "unclassified": "dark-gray",
    "living_street": "dark-gray",
    "service": "dark-gray",
    "pedestrian": "gray",
    "track": "dark-gray",
    "path": "gray",
    "footway": "gray",
    "cycleway": "dark-gray",
    "bridleway": "gray",
    "steps": "gray",
    "crossing": "dark-gray",
    "proposed": "dark-gray",
    "route": "dark-gray",
    "traffic_signals": "red",
    "give_way": "red",
    "roundabout": "dark-gray",
    "bus_stop": "dark-gray",
    # default color for roadline class subtypes
    "roadline": "white",
    "solid": "white",
    "curbstone": "light-gray",
    "road_border": "light-gray",
    # default color for vehicle class subtypes
    "vehicle": "light-turquoise",
    "car": "light-turquoise",
    "truck": "light-turquoise",
    # default color for cyclist class subtypes
    "motorcycle": "light-orange",
    "cyclist": "light-orange",
    "bicycle": "light-orange",
    # default color for pedestrian class subtypes
    "pedestrian": "light-blue",
    # default color for lidar point cloud
    "lidar_point_cloud": "red",
    # unclassified / fallback
    "multipolygon": "black",
}

DEFAULT_ORDER = {
    # default zorder for lane class subtypes
    "lane": 3,
    "slipLane": 3,
    "road": 3,
    "driving": 3,
    "bidirectional": 3,
    "highway": 3,
    "play_street": 3,
    "emergency_lane": 3,
    "bus_lane": 2,
    "bus": 2,
    "bicycle_lane": 2,
    "biking": 2,
    "exit": 3,
    "entry": 3,
    "offRamp": 3,
    "onRamp": 3,
    "walkway": 3,
    "shared_walkway": 3,
    "crosswalk": 2,
    "stairs": 3,
    # default zorder for junction class subtypes
    # rendered below lanes (zorder 3) so lane polygons sit on top of the
    # junction fill, keeping road markings visible at intersections
    "junction": 2,
    "priority": 2,
    "traffic_light": 2,
    "right_before_left": 2,
    "unregulated": 2,
    "dead_end": 2,
    "rail_signal": 2,
    "zipper": 2,
    "rail_crossing": 2,
    "allway_stop": 2,
    # default zorder for area class subtypes
    "area": 2,
    "hole": 3,
    "parking": 3,
    "parkingSpace": 3,
    "freespace": 3,
    "vegetation": 3,
    "keepout": 3,
    "building": 2,
    "traffic_island": 3,
    "obstacle": 5,
    # area subtypes from standard OSM tags (render below roads at zorder 4)
    "commercial": 2,
    "retail": 2,
    "industrial": 2,
    "shelter": 2,
    "swimming_pool": 2,
    "park": 3,
    "grass": 3,
    "water": 2,
    "wood": 3,
    "multipolygon": 2,
    # road types from standard OSM highway tags
    "motorway": 4,
    "motorway_link": 4,
    "trunk": 4,
    "trunk_link": 4,
    "primary": 4,
    "primary_link": 4,
    "secondary": 4,
    "secondary_link": 4,
    "tertiary": 4,
    "tertiary_link": 4,
    "residential": 4,
    "unclassified": 4,
    "living_street": 4,
    "service": 4,
    "pedestrian": 3,
    "track": 4,
    "path": 3,
    "footway": 3,
    "cycleway": 4,
    "bridleway": 3,
    "steps": 3,
    "crossing": 2,
    "proposed": 4,
    "route": 4,
    "traffic_signals": 2,
    "give_way": 2,
    "roundabout": 4,
    "bus_stop": 4,
    # default zorder for roadline class subtypes
    "roadline": 4,
    "solid": 4,
    "dashed": 4,
    "road_border": 4,
    "curbstone": 5,
    "vehicle": 6,
    "car": 6,
    "truck": 6,
    "heading_arrow": 7,
    # default zorder for lidar point cloud
    "lidar_point_cloud": 8,
    # default zorder for cyclist class subtypes
    "motorcycle": 6,
    "cyclist": 6,
    "bicycle": 6,
    # default zorder for pedestrian class subtypes
    "pedestrian": 6,
}
