# Copyright (C) 2026, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""Socket-driven roundabout generator.

Roundabout v1 follows the RoadPort/reference-line workflow:
1. The roundabout module owns the circular ring and fixed circular sockets.
2. Approach curvature is generated by external road modules connected to sockets.
3. Connector lane boundaries are kept virtual to avoid visual petal artefacts.
4. Short visible arm-edge roadlines close the seam with connected road modules.
"""

from __future__ import annotations

from typing import Any

import numpy as np

from tactics2d.geometry import heading_unit, offset_polyline
from tactics2d.map.element import Lane, RoadLine
from tactics2d.map.generator.rules.lane_marking_rules import roadline_render_kwargs, roundabout_mark
from tactics2d.map.generator.rules.module_types import RoadModuleResult, RoadPort

from .element_builder import (
    add_ordered_lane_neighbors,
    build_junction_arm_ports,
    build_lane_from_boundaries,
    build_pavement_junction,
    build_roadline_from_points,
)
from .reference_line import arc_pts, bezier_connection
from .road_segment import RoadSegment


def _ring_arc_points(
    center: np.ndarray,
    radius: float,
    start_angle: float,
    end_angle: float,
    clockwise: bool = True,
    step_size: float = 0.1,
) -> np.ndarray:
    """Sample a circular arc between two angular positions.

    Args:
        center: Circle centre in world coordinates.
        radius: Circle radius in metres.
        start_angle: Start polar angle in radians.
        end_angle: End polar angle in radians.
        clockwise: When ``True`` the arc runs clockwise (the default for
            roundabout ring road lanes in standard driving conventions).
        step_size: Desired sampling interval in metres.

    Returns:
        Sampled arc points with shape ``(N, 2)``.
    """
    center = np.asarray(center, dtype=float)
    radius = float(radius)

    if clockwise:
        delta = (float(start_angle) - float(end_angle)) % (2.0 * np.pi)
        start_heading = float(start_angle) - np.pi / 2.0
    else:
        delta = (float(end_angle) - float(start_angle)) % (2.0 * np.pi)
        start_heading = float(start_angle) + np.pi / 2.0

    if delta < 1e-6:
        delta = 2.0 * np.pi

    start_pt = center + radius * np.array([np.cos(start_angle), np.sin(start_angle)], dtype=float)

    pts, _ = arc_pts(
        start_pt=start_pt,
        start_heading=start_heading,
        angle=delta,
        radius=radius,
        clockwise=clockwise,
        step_size=step_size,
    )

    return pts


def _normalize_roundabout_arm(
    center: np.ndarray,
    arm: dict[str, Any] | RoadPort,
    default_radius: float,
    default_lane_width: float,
    default_speed_limit: float,
) -> dict[str, Any]:
    """Convert an arm descriptor into a fixed circular roundabout socket.

    Dict arms are projected directly onto the circular outer boundary using
    ``heading_unit()``; the optional ``curvature`` field is stored as metadata
    only and does not move the socket.  Curved approach roads should be generated
    by external ``OneWay`` / ``TwoWay`` modules connected to the returned port.

    This differs from :func:`intersection._normalize_intersection_arm`, which
    places the socket via ``sample_centerline()`` so that non-zero curvature
    actually shifts the boundary point.

    Args:
        center: Roundabout centre in world coordinates.
        arm: Arm descriptor — either a :class:`RoadPort` or a ``dict`` with
            keys ``"heading"`` and ``"lane_num"``, and optionally ``"radius"``,
            ``"curvature"``, ``"lane_width"``, ``"speed_limit"``.
        default_radius: Fallback outer-ring boundary radius in metres.
        default_lane_width: Fallback lane width in metres.
        default_speed_limit: Fallback speed limit in km/h.

    Returns:
        Dict with keys ``"point"``, ``"heading_outward"``, ``"heading_inward"``,
        ``"lane_num"``, ``"lane_width"``, ``"speed_limit"``, ``"curvature"``,
        and ``"radius"``.

    Raises:
        ValueError: If a dict arm is missing ``"heading"`` or ``"lane_num"``.
    """
    if isinstance(arm, RoadPort):
        point = np.asarray(arm.point, dtype=float)
        heading_outward = float(arm.heading)

        return {
            "point": point,
            "heading_outward": heading_outward,
            "heading_inward": heading_outward + np.pi,
            "lane_num": int(arm.lane_num),
            "lane_width": float(arm.lane_width),
            "speed_limit": float(arm.speed_limit),
            "curvature": 0.0,
            "radius": float(np.linalg.norm(point - center)),
        }

    if "heading" not in arm or "lane_num" not in arm:
        raise ValueError("Each arm dict must contain 'heading' and 'lane_num'.")

    heading_outward = float(arm["heading"])
    arm_radius = float(arm.get("radius", default_radius))
    lane_width = float(arm.get("lane_width", default_lane_width))
    point = center + arm_radius * heading_unit(heading_outward)

    return {
        "point": point,
        "heading_outward": heading_outward,
        "heading_inward": heading_outward + np.pi,
        "lane_num": int(arm["lane_num"]),
        "lane_width": lane_width,
        "speed_limit": float(arm.get("speed_limit", default_speed_limit)),
        "curvature": float(arm.get("curvature", 0.0)),
        "radius": arm_radius,
    }


def _roundabout_junction_shape(
    center: np.ndarray, outer_radius: float, step_size: float
) -> list[tuple[float, float]]:
    """Create a closed circular polygon for the roundabout pavement junction.

    Args:
        center: Circle centre in world coordinates.
        outer_radius: Outer ring radius in metres.
        step_size: Desired arc sampling interval in metres (used to compute
            the number of polygon vertices).

    Returns:
        Closed polygon vertex list as ``[(x, y), ...]`` with the first point
        repeated at the end.
    """
    n = max(64, int(2.0 * np.pi * outer_radius / max(step_size, 1e-6)))
    angles = np.linspace(0.0, 2.0 * np.pi, n, endpoint=False)

    pts = [
        (
            float(center[0] + outer_radius * np.cos(angle)),
            float(center[1] + outer_radius * np.sin(angle)),
        )
        for angle in angles
    ]
    pts.append(pts[0])

    return pts


def _virtual_connection_roadline(id_: int, points: np.ndarray, role: str, side: str) -> RoadLine:
    """Create a non-rendered connector boundary RoadLine for a roundabout arm.

    Virtual roadlines are required by ``Lane.line_ids`` but must not be
    drawn as visible lane markings inside the roundabout ring.  The
    ``type_``/``subtype`` kwargs override the token-derived defaults so the
    roadline is suppressed by renderers that filter on ``type_="virtual"``.

    Args:
        id_: RoadLine id.
        points: Boundary polyline points.
        role: Semantic role tag (e.g. ``"entry_connection_boundary"``).
        side: ``"left"`` or ``"right"``.

    Returns:
        A :class:`RoadLine` with ``type_="virtual"``.
    """
    return build_roadline_from_points(
        id_=id_,
        points=points,
        marking_kwargs=roadline_render_kwargs(
            roundabout_mark("connection"), {"module": "roundabout", "role": role, "side": side}
        ),
        type_="virtual",
        subtype="virtual",
    )


def _build_connector_lane(
    kind: str,
    p_start: np.ndarray,
    h_start: float,
    p_end: np.ndarray,
    h_end: float,
    arm_lane_width: float,
    arm_speed: float,
    speed_limit: float,
    arm_idx: int,
    lane_i: int,
    step_size: float,
    id_counter: int,
) -> tuple[Lane, list[RoadLine], int]:
    """Build one connector lane (entry or exit) between the arm and the ring road.

    Args:
        kind: ``"entry"`` or ``"exit"``.
        p_start: Connector start point.
        h_start: Heading at ``p_start``.
        p_end: Connector end point.
        h_end: Heading at ``p_end``.
        arm_lane_width: Width of a single arm lane in metres.
        arm_speed: Arm speed limit in km/h.
        speed_limit: Ring speed limit in km/h.
        arm_idx: Arm index for tagging.
        lane_i: Lane index within the arm for tagging.
        step_size: Bezier curve sampling interval in metres.
        id_counter: Current element id counter.

    Returns:
        Tuple ``(lane, [left_roadline, right_roadline], updated_id_counter)``.
    """
    centerline = bezier_connection(p_start, h_start, p_end, h_end, step_size, min_tangent=0.0)
    left_pts = offset_polyline(centerline, arm_lane_width / 2.0)
    right_pts = offset_polyline(centerline, -arm_lane_width / 2.0)

    left_rl = _virtual_connection_roadline(
        id_=id_counter, points=left_pts, role=f"{kind}_connection_boundary", side="left"
    )
    id_counter += 1

    right_rl = _virtual_connection_roadline(
        id_=id_counter, points=right_pts, role=f"{kind}_connection_boundary", side="right"
    )
    id_counter += 1

    lane = build_lane_from_boundaries(
        id_=id_counter,
        left_points=left_pts,
        right_points=right_pts,
        left_roadline_ids=left_rl.id_,
        right_roadline_ids=right_rl.id_,
        speed_limit=min(speed_limit, arm_speed),
        custom_tags={"module": "roundabout", "arm": arm_idx, "type": kind, "lane_index": lane_i},
    )
    id_counter += 1

    return lane, [left_rl, right_rl], id_counter


def _arm_opening_half_angle(arm: dict[str, Any], outer_ring_radius: float) -> float:
    """Return the circular opening half-angle induced by an arm throat width.

    The half-angle is derived from the arm's full lane-count width projected
    onto the outer ring via ``arcsin``; it determines how much of the ring arc
    is reserved for each arm opening.

    Args:
        arm: Normalised arm record with ``"lane_num"`` and ``"lane_width"`` keys.
        outer_ring_radius: Outer edge radius of the ring road in metres.

    Returns:
        Half-angle in radians subtended by the arm throat on the outer ring.
    """
    throat_width = int(arm["lane_num"]) * float(arm["lane_width"])

    if outer_ring_radius <= 1e-9:
        return np.pi / 8.0

    ratio = float(np.clip(throat_width / outer_ring_radius, 1e-6, 0.95))
    return float(np.arcsin(ratio))


def _ray_circle_intersection(
    start: np.ndarray, direction: np.ndarray, center: np.ndarray, radius: float
) -> np.ndarray:
    """Return the nearest forward intersection of a ray with a circle.

    Args:
        start: Ray origin in world coordinates.
        direction: Ray direction vector (need not be normalised).
        center: Circle centre in world coordinates.
        radius: Circle radius in metres.

    Returns:
        Intersection point ``(x, y)``. Returns ``start`` when there is no
        forward intersection or the direction vector is degenerate.
    """
    start = np.asarray(start, dtype=float)
    direction = np.asarray(direction, dtype=float)
    center = np.asarray(center, dtype=float)

    norm = float(np.linalg.norm(direction))
    if norm < 1e-9:
        return start.copy()

    direction = direction / norm
    p = start - center

    a = float(np.dot(direction, direction))
    b = 2.0 * float(np.dot(p, direction))
    c = float(np.dot(p, p) - radius * radius)

    discriminant = b * b - 4.0 * a * c
    if discriminant < 0.0:
        return start.copy()

    sqrt_discriminant = float(np.sqrt(discriminant))
    t1 = (-b - sqrt_discriminant) / (2.0 * a)
    t2 = (-b + sqrt_discriminant) / (2.0 * a)

    candidates = [t for t in (t1, t2) if t >= 0.0]
    if len(candidates) == 0:
        return start.copy()

    t = min(candidates)
    return start + t * direction


def _arm_outer_edge_roadlines(
    center: np.ndarray, arm: dict[str, Any], arm_idx: int, outer_ring_radius: float, id_counter: int
) -> tuple[list[RoadLine], int]:
    """Create short visible road-edge lines at the junction between an arm and the ring.

    The lines run along the connected road boundary direction and terminate
    where they meet the outer ring circle, avoiding diagonal artefacts.

    Args:
        center: Roundabout centre in world coordinates.
        arm: Normalised arm record from :func:`_normalize_roundabout_arm`.
        arm_idx: Arm index used in ``custom_tags``.
        outer_ring_radius: Outer radius of the ring road in metres.
        id_counter: Starting id counter.

    Returns:
        Tuple ``(roadlines, updated_id_counter)`` with up to 2 RoadLines.
    """
    boundary_pt = np.asarray(arm["point"], dtype=float)
    h_in = float(arm["heading_inward"])
    h_out = float(arm["heading_outward"])

    lane_num = int(arm["lane_num"])
    lane_width = float(arm["lane_width"])

    normal = np.array([-np.sin(h_in), np.cos(h_in)], dtype=float)

    positive_edge_start = boundary_pt + lane_num * lane_width * normal
    negative_edge_start = boundary_pt - lane_num * lane_width * normal

    inward_direction = -heading_unit(h_out)

    positive_edge_end = _ray_circle_intersection(
        start=positive_edge_start,
        direction=inward_direction,
        center=center,
        radius=outer_ring_radius,
    )
    negative_edge_end = _ray_circle_intersection(
        start=negative_edge_start,
        direction=inward_direction,
        center=center,
        radius=outer_ring_radius,
    )

    edge_specs = [
        ("positive_outer_edge", np.vstack([positive_edge_start, positive_edge_end])),
        ("negative_outer_edge", np.vstack([negative_edge_start, negative_edge_end])),
    ]

    roadlines: list[RoadLine] = []

    for role, points in edge_specs:
        if np.linalg.norm(points[-1] - points[0]) < 1e-6:
            continue

        roadline = build_roadline_from_points(
            id_=id_counter,
            points=points,
            marking_kwargs=roadline_render_kwargs(
                roundabout_mark("ring_outer"),
                {
                    "module": "roundabout",
                    "role": "arm_outer_edge",
                    "edge_role": role,
                    "arm": arm_idx,
                    "render_width": 0.6,
                },
            ),
        )
        id_counter += 1
        roadlines.append(roadline)

    return roadlines, id_counter


def _roundabout_build(
    center: np.ndarray,
    arms: list[dict[str, Any] | RoadPort],
    ring_radius: float,
    ring_lane_num: int,
    lane_width: float,
    speed_limit: float,
    step_size: float,
    id_offset: int,
) -> RoadModuleResult:
    """Build all ring lanes, connector lanes, and ports for a roundabout.

    This function is the single implementation backing
    :class:`Roundabout`. It generates circulating ring-road segments
    between arm openings, Bezier entry/exit connector lanes for each arm,
    short seam-closure edge roadlines, and a circular junction pavement.

    Args:
        center: Roundabout centre in world coordinates.
        arms: At least 2 arm descriptors; each element is a :class:`RoadPort`
            or a ``dict`` with keys ``"heading"``, ``"lane_num"``, and
            optionally ``"radius"``, ``"curvature"``, ``"lane_width"``,
            ``"speed_limit"``.
        ring_radius: Inner edge radius of the ring road in metres.
        ring_lane_num: Number of circulating lanes in the ring.
        lane_width: Lane width in metres for both ring and arm connectors.
        speed_limit: Speed limit in km/h applied to ring and connector lanes.
        step_size: Arc sampling interval in metres.
        id_offset: Starting id counter.

    Returns:
        :class:`RoadModuleResult` with ports ``"arm_{i}_in"`` and
        ``"arm_{i}_out"`` for each arm index and a single junction element.

    Raises:
        ValueError: If fewer than 2 arms are provided, ``ring_lane_num < 1``,
            ``lane_width <= 0``, ``ring_radius <= 0``, or ``step_size <= 0``.
    """
    center = np.asarray(center, dtype=float)

    if len(arms) < 2:
        raise ValueError("roundabout requires at least 2 arms.")
    if ring_lane_num < 1:
        raise ValueError("ring_lane_num must be >= 1.")
    if lane_width <= 0.0:
        raise ValueError("lane_width must be positive.")
    if ring_radius <= 0.0:
        raise ValueError("ring_radius must be positive.")
    if step_size <= 0.0:
        raise ValueError("step_size must be positive.")

    outer_ring_radius = ring_radius + ring_lane_num * lane_width
    normalized_arms = [
        _normalize_roundabout_arm(
            center=center,
            arm=arm,
            default_radius=outer_ring_radius,
            default_lane_width=lane_width,
            default_speed_limit=speed_limit,
        )
        for arm in arms
    ]

    for i, arm in enumerate(normalized_arms):
        if arm["lane_num"] < 1:
            raise ValueError(f"arm[{i}] lane_num must be >= 1.")
        if arm["lane_width"] <= 0.0:
            raise ValueError(f"arm[{i}] lane_width must be positive.")

    n_arms = len(normalized_arms)
    id_counter = id_offset

    lanes: list[Lane] = []
    roadlines: list[RoadLine] = []

    sorted_indices = sorted(
        range(n_arms),
        key=lambda idx: normalized_arms[idx]["heading_outward"] % (2.0 * np.pi),
        reverse=True,
    )

    opening_half_angles = [
        _arm_opening_half_angle(arm, outer_ring_radius) for arm in normalized_arms
    ]

    entry_offsets = [0.6 * angle for angle in opening_half_angles]
    exit_offsets = [0.6 * angle for angle in opening_half_angles]

    for seg_i in range(n_arms):
        curr_idx = sorted_indices[seg_i]
        next_idx = sorted_indices[(seg_i + 1) % n_arms]

        curr_angle = normalized_arms[curr_idx]["heading_outward"] % (2.0 * np.pi)
        next_angle = normalized_arms[next_idx]["heading_outward"] % (2.0 * np.pi)

        seg_start = curr_angle - opening_half_angles[curr_idx]
        seg_end = next_angle + opening_half_angles[next_idx]

        seg_lanes: list[Lane] = []

        for lane_i in range(ring_lane_num):
            inner_radius = ring_radius + lane_i * lane_width
            outer_radius = ring_radius + (lane_i + 1) * lane_width
            center_radius = ring_radius + (lane_i + 0.5) * lane_width

            outer_arc = _ring_arc_points(
                center=center,
                radius=outer_radius,
                start_angle=seg_start,
                end_angle=seg_end,
                clockwise=True,
                step_size=step_size,
            )
            inner_arc = _ring_arc_points(
                center=center,
                radius=inner_radius,
                start_angle=seg_start,
                end_angle=seg_end,
                clockwise=True,
                step_size=step_size,
            )
            center_arc = _ring_arc_points(
                center=center,
                radius=center_radius,
                start_angle=seg_start,
                end_angle=seg_end,
                clockwise=True,
                step_size=step_size,
            )
            is_outermost = lane_i == ring_lane_num - 1
            is_innermost = lane_i == 0

            outer_role = "ring_outer" if is_outermost else "ring_interior"
            inner_role = "ring_inner" if is_innermost else "ring_interior"

            outer_roadline = build_roadline_from_points(
                id_=id_counter,
                points=outer_arc,
                marking_kwargs=roadline_render_kwargs(
                    roundabout_mark(outer_role),
                    {
                        "segment": seg_i,
                        "ring_lane_index": lane_i,
                        "side": "outer",
                        "render_width": 0.6,
                    },
                ),
            )
            id_counter += 1

            inner_roadline = build_roadline_from_points(
                id_=id_counter,
                points=inner_arc,
                marking_kwargs=roadline_render_kwargs(
                    roundabout_mark(inner_role),
                    {
                        "segment": seg_i,
                        "ring_lane_index": lane_i,
                        "side": "inner",
                        "render_width": 0.6,
                    },
                ),
            )
            id_counter += 1

            ring_lane = build_lane_from_boundaries(
                id_=id_counter,
                left_points=outer_arc,
                right_points=inner_arc,
                left_roadline_ids=outer_roadline.id_,
                right_roadline_ids=inner_roadline.id_,
                speed_limit=speed_limit,
                custom_tags={
                    "module": "roundabout",
                    "segment": seg_i,
                    "ring_lane_index": lane_i,
                    "from_arm": curr_idx,
                    "to_arm": next_idx,
                },
            )
            id_counter += 1

            lanes.append(ring_lane)
            roadlines.extend([outer_roadline, inner_roadline])
            seg_lanes.append(ring_lane)

        add_ordered_lane_neighbors(seg_lanes)

    incoming_lane_ids: list[list[str]] = [[] for _ in range(n_arms)]
    outgoing_lane_ids: list[list[str]] = [[] for _ in range(n_arms)]

    for arm_idx, arm in enumerate(normalized_arms):
        h_in = float(arm["heading_inward"])
        h_out = float(arm["heading_outward"])
        boundary_pt = np.asarray(arm["point"], dtype=float)
        arm_lane_num = int(arm["lane_num"])
        arm_lane_width = float(arm["lane_width"])
        arm_speed = float(arm["speed_limit"])
        pair_num = min(arm_lane_num, ring_lane_num)

        normal = np.array([-np.sin(h_in), np.cos(h_in)], dtype=float)
        arm_angle = h_out % (2.0 * np.pi)

        for lane_i in range(pair_num):
            ring_center_radius = ring_radius + (lane_i + 0.5) * lane_width

            entry_angle = arm_angle + entry_offsets[arm_idx]
            entry_contact = center + ring_center_radius * np.array(
                [np.cos(entry_angle), np.sin(entry_angle)], dtype=float
            )
            entry_heading_clockwise = entry_angle - np.pi / 2.0
            arm_entry_pt = boundary_pt - (lane_i + 0.5) * arm_lane_width * normal

            entry_lane, entry_rls, id_counter = _build_connector_lane(
                "entry",
                arm_entry_pt,
                h_in,
                entry_contact,
                entry_heading_clockwise,
                arm_lane_width,
                arm_speed,
                speed_limit,
                arm_idx,
                lane_i,
                step_size,
                id_counter,
            )
            lanes.append(entry_lane)
            roadlines.extend(entry_rls)
            outgoing_lane_ids[arm_idx].append(entry_lane.id_)

            exit_angle = arm_angle - exit_offsets[arm_idx]
            exit_contact = center + ring_center_radius * np.array(
                [np.cos(exit_angle), np.sin(exit_angle)], dtype=float
            )
            exit_heading_clockwise = exit_angle - np.pi / 2.0
            arm_exit_pt = boundary_pt + (lane_i + 0.5) * arm_lane_width * normal

            exit_lane, exit_rls, id_counter = _build_connector_lane(
                "exit",
                exit_contact,
                exit_heading_clockwise,
                arm_exit_pt,
                h_out,
                arm_lane_width,
                arm_speed,
                speed_limit,
                arm_idx,
                lane_i,
                step_size,
                id_counter,
            )
            lanes.append(exit_lane)
            roadlines.extend(exit_rls)
            incoming_lane_ids[arm_idx].append(exit_lane.id_)

    for arm_idx, arm in enumerate(normalized_arms):
        edge_roadlines, id_counter = _arm_outer_edge_roadlines(
            center=center,
            arm=arm,
            arm_idx=arm_idx,
            outer_ring_radius=outer_ring_radius,
            id_counter=id_counter,
        )
        roadlines.extend(edge_roadlines)

    junction_shape = _roundabout_junction_shape(
        center=center, outer_radius=outer_ring_radius, step_size=step_size
    )

    junction = build_pavement_junction(
        id_=id_counter,
        shape_points=junction_shape,
        center=center,
        junction_type="roundabout",
        sumo_type="priority",
        custom_tags={
            "ring_radius": float(ring_radius),
            "outer_ring_radius": float(outer_ring_radius),
            "ring_lane_num": int(ring_lane_num),
        },
    )
    id_counter += 1

    ports = build_junction_arm_ports(
        normalized_arms=normalized_arms,
        outgoing_lane_ids=outgoing_lane_ids,
        incoming_lane_ids=incoming_lane_ids,
        module_name="roundabout",
    )

    return RoadModuleResult(
        lanes=lanes, roadlines=roadlines, junctions=[junction], ports=ports, id_counter=id_counter
    )


class Roundabout(RoadSegment):
    """Roundabout generator with a circulating ring road.

    Each arm socket is placed on the circular outer boundary of the ring road.
    Connect ``TwoWay`` or ``OneWay`` segments to the returned arm ports to
    produce curved approach roads.

    Attributes:
        ring_radius: Radius of the inner edge of the ring road in metres.
        ring_lane_num: Number of circulating lanes in the ring.
        lane_width: Lane width in metres (uniform for ring and arm stubs).
        speed_limit: Speed limit in km/h (applied to ring and arm stubs).
        step_size: Arc sampling interval in metres.
    """

    def __init__(
        self,
        ring_radius: float = 15.0,
        ring_lane_num: int = 1,
        lane_width: float = 3.5,
        speed_limit: float = 20.0,
        step_size: float = 0.1,
    ) -> None:
        """Initialise the generator.

        Args:
            ring_radius: Radius of the inner edge of the ring road in metres.
            ring_lane_num: Number of circulating lanes in the ring.
            lane_width: Lane width in metres.
            speed_limit: Speed limit in km/h.
            step_size: Arc sampling interval in metres.

        Raises:
            ValueError: If ``ring_lane_num < 1``, ``lane_width <= 0``,
                ``ring_radius <= 0``, or ``step_size <= 0``.
        """
        if ring_lane_num < 1:
            raise ValueError("ring_lane_num must be >= 1.")
        if lane_width <= 0.0:
            raise ValueError("lane_width must be positive.")
        if ring_radius <= 0.0:
            raise ValueError("ring_radius must be positive.")
        if step_size <= 0.0:
            raise ValueError("step_size must be positive.")
        self.ring_radius = ring_radius
        self.ring_lane_num = ring_lane_num
        self.lane_width = lane_width
        self.speed_limit = speed_limit
        self.step_size = step_size

    def build(
        self, center: np.ndarray, arms: list[dict[str, Any] | RoadPort], *, id_offset: int = 0
    ) -> RoadModuleResult:
        """Build a roundabout from the given centre and arm descriptors.

        Args:
            center: 2-D world coordinate of the roundabout centre.
            arms: List of arm descriptors. Each element is either a
                :class:`RoadPort` or a plain ``dict`` with keys ``"heading"``,
                ``"lane_num"``, and optionally ``"lane_width"``,
                ``"speed_limit"``.
            id_offset: First element id.

        Returns:
            :class:`RoadModuleResult` containing ring-road lanes, arm-stub
            lanes, roadlines, a junction polygon, and one named port per arm
            keyed as ``"arm_0"``, ``"arm_1"``, ….

        Raises:
            ValueError: If fewer than 2 arms are supplied, or any arm has
                invalid ``lane_num`` or ``lane_width``.
        """
        return _roundabout_build(
            center=center,
            arms=arms,
            ring_radius=self.ring_radius,
            ring_lane_num=self.ring_lane_num,
            lane_width=self.lane_width,
            speed_limit=self.speed_limit,
            step_size=self.step_size,
            id_offset=id_offset,
        )
