# Copyright (C) 2024, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""OSM parser implementation."""

from __future__ import annotations

import logging
import math

import defusedxml.ElementTree as ET
from pyproj import Proj
from shapely.geometry import LineString, Polygon

from tactics2d.map.element import Area, Lane, Map, Node, Regulatory, RoadLine


class OSMParser:
    """This class implements a parser for the original OpenStreetMap format map. The parser is tested with data generated by the official OpenStreetMap website and the JOSM software application.

    Example:
        >>> parser = OSMParser()
        >>> map_ = parser.parse("/path/to/map.osm")
        >>> parser_l2 = OSMParser(lanelet2=True)
        >>> map_l2 = parser_l2.parse("/path/to/map_lanelet2.osm")
    """

    def __init__(self, lanelet2: bool = False):
        """Initialize the parser.

        Args:
            lanelet2 (bool): Whether the `.osm` file is annotated in Lanelet2 format.
                Defaults to False.
        """
        self.lanelet2 = lanelet2
        self._way_id_map = {}
        self._relation_id_map = {}

    def _mapped_way_id(self, id_: int) -> int:
        return self._way_id_map.get(id_, id_)

    def _mapped_relation_id(self, id_: int) -> int:
        return self._relation_id_map.get(id_, id_)

    def _build_id_remaps(self, xml_root: ET.Element) -> None:
        """Remap way/relation ids that collide with other element kinds.

        OSM keeps node, way, and relation ids in independent namespaces, while
        :class:`Map` enforces a single one; official levelXdata lanelet2 maps
        reuse numeric ids across kinds (e.g. exiD node 1500 vs way 1500).
        Colliding ways and relations get ids from a free range, and every
        member reference is resolved through the same tables, so maps without
        collisions keep their original ids untouched.
        """
        node_ids = {int(node.attrib["id"]) for node in xml_root.findall("node")}
        way_ids = [int(way.attrib["id"]) for way in xml_root.findall("way")]
        relation_ids = [int(relation.attrib["id"]) for relation in xml_root.findall("relation")]

        self._way_id_map = {}
        self._relation_id_map = {}
        used = set(node_ids)
        next_id = max(used.union(way_ids, relation_ids), default=0) + 1

        for way_id in way_ids:
            if way_id in used:
                self._way_id_map[way_id] = next_id
                used.add(next_id)
                next_id += 1
            else:
                used.add(way_id)

        for relation_id in relation_ids:
            if relation_id in used:
                self._relation_id_map[relation_id] = next_id
                used.add(next_id)
                next_id += 1
            else:
                used.add(relation_id)

        if self._way_id_map or self._relation_id_map:
            logging.warning(
                "%d way id(s) and %d relation id(s) collide with other element kinds; "
                "remapped them to a free id range.",
                len(self._way_id_map),
                len(self._relation_id_map),
            )

    def _append_point_list(self, point_list: list, new_points: list, component_id: int) -> None:
        """Append new points to an existing point list, handling direction alignment.

        Args:
            point_list (list): Existing list of points to append to.
            new_points (list): New points to append.
            component_id (int): The id of the component, used for error messages.

        Raises:
            SyntaxError: If the points are not continuous.
        """
        if point_list[-1] == new_points[0]:
            pass
        elif point_list[0] == new_points[0]:
            point_list.reverse()
        elif point_list[0] == new_points[-1]:
            point_list.reverse()
            new_points.reverse()
        elif point_list[-1] == new_points[-1]:
            new_points.reverse()
        else:
            raise SyntaxError(f"Points on the side of relation {component_id} is not continuous.")

        point_list += new_points[1:]

    def _stitch_polylines(self, segments: list, component_id: int) -> list:
        """Stitch member polylines into one chain regardless of member order.

        Official lanelet2 exports do not guarantee that relation members are
        listed head-to-tail, so segments are joined by matching endpoints in
        any order and orientation. When no exact match remains, the chain is
        bridged to the nearest remaining segment with a warning instead of
        aborting the whole map.

        Args:
            segments (list): Lists of points, one per relation member.
            component_id (int): The id of the relation, used for messages.

        Returns:
            list: The stitched point chain.
        """
        segments = [list(segment) for segment in segments if len(segment) > 0]
        if not segments:
            return []

        chain = segments.pop(0)
        while segments:
            joined = False
            for index, segment in enumerate(segments):
                try:
                    self._append_point_list(chain, list(segment), component_id)
                except SyntaxError:
                    continue
                segments.pop(index)
                joined = True
                break
            if joined:
                continue

            best_cost = None
            best = None
            for index, segment in enumerate(segments):
                for chain_flip, chain_end in ((False, chain[-1]), (True, chain[0])):
                    for segment_flip, segment_start in ((False, segment[0]), (True, segment[-1])):
                        cost = (chain_end[0] - segment_start[0]) ** 2 + (
                            chain_end[1] - segment_start[1]
                        ) ** 2
                        if best_cost is None or cost < best_cost:
                            best_cost = cost
                            best = (index, chain_flip, segment_flip)

            index, chain_flip, segment_flip = best
            segment = segments.pop(index)
            if chain_flip:
                chain.reverse()
            if segment_flip:
                segment.reverse()
            logging.warning(
                "Members of relation %s are not connected; bridging a gap of %.2f m.",
                component_id,
                best_cost**0.5,
            )
            chain += segment

        return chain

    def _get_tags(self, xml_node: ET.Element) -> dict:
        """Parse OSM tags from an XML node into a dictionary.

        Args:
            xml_node (ET.Element): The XML node containing tag elements.

        Returns:
            dict: Parsed tags with boolean conversion for area and oneway keys.
        """
        tags = {}
        bool_tags = {"area", "oneway"}

        for tag in xml_node.findall("tag"):
            if tag.attrib["k"] in bool_tags:
                tags[tag.attrib["k"]] = tag.attrib["v"] == "yes"
            else:
                tags[tag.attrib["k"]] = tag.attrib["v"]

        return tags

    def _get_lanelet2_tags(self, xml_node: ET.Element) -> dict:
        """Parse Lanelet2 tags from an XML node into a structured dictionary.

        Args:
            xml_node (ET.Element): The XML node containing Lanelet2 tag elements.

        Returns:
            dict: Parsed tags with type conversion for speed_limit and boolean
                conversion for bool_tags. Lane change attributes are stored as
                tuples in custom_tags.
        """
        tags = {}
        tags["custom_tags"] = {}

        directly_save = {
            "subtype",
            "color",
            "width",
            "location",
            "inferred_participants",
            "speed_limit",
        }
        bool_tags = {"temporary", "speed_limit_mandatory", "dynamic", "fallback", "oneway"}

        for tag in xml_node.findall("tag"):
            if tag.attrib["k"] == "type":
                tags["type_"] = tag.attrib["v"]

            elif tag.attrib["k"] in directly_save:
                if tag.attrib["k"] == "speed_limit":
                    try:
                        tags["speed_limit"] = float(tag.attrib["v"])
                    except (ValueError, TypeError):
                        logging.warning("Invalid speed_limit value: %s", tag.attrib["v"])
                else:
                    tags[tag.attrib["k"]] = tag.attrib["v"]

            elif tag.attrib["k"] in bool_tags:
                tags["custom_tags"][tag.attrib["k"]] = tag.attrib["v"] == "yes"

            elif "lane_change" in tag.attrib["k"]:
                if "lane_change" in tags["custom_tags"]:
                    raise SyntaxError("Conflict tags on lane changing property.")
                else:
                    if tag.attrib["k"] == "lane_change":
                        tags["custom_tags"]["lane_change"] = (
                            (True, True) if tag.attrib["v"] == "yes" else (False, False)
                        )
                    elif tag.attrib["k"] == "lane_change:left":
                        tags["custom_tags"]["lane_change"] = (
                            (True, False) if tag.attrib["v"] == "yes" else (False, False)
                        )
                    elif tag.attrib["k"] == "lane_change:right":
                        tags["custom_tags"]["lane_change"] = (
                            (False, True) if tag.attrib["v"] == "yes" else (False, False)
                        )

            else:
                tags["custom_tags"][tag.attrib["k"]] = tag.attrib["v"]

        return tags

    def _parse_area(self, xml_node: ET.Element, map_: Map) -> Area:
        """Parse an OSM area element from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the area.
            map_ (Map): The map that the area belongs to.

        Returns:
            Area: The parsed area, or None if the outer boundary is empty or parsing fails.
        """
        area_id = self._mapped_relation_id(int(xml_node.attrib["id"]))
        line_ids = dict(inner=[], outer=[])
        regulatory_ids = []

        for member in xml_node.findall("member"):
            member_id = int(member.attrib["ref"])
            if member.attrib["role"] == "outer":
                line_ids["outer"].append(self._mapped_way_id(member_id))
            elif member.attrib["role"] == "inner":
                line_ids["inner"].append(self._mapped_way_id(member_id))
            elif member.attrib["role"] == "regulatory_element":
                regulatory_ids.append(self._mapped_relation_id(member_id))

        outer_point_list = []
        for line_id in line_ids["outer"]:
            if len(outer_point_list) == 0:
                if map_.roadlines.get(line_id):
                    outer_point_list = list(map_.roadlines[line_id].geometry.coords)
            else:
                if map_.roadlines.get(line_id):
                    new_points = list(map_.roadlines[line_id].geometry.coords)
                    try:
                        self._append_point_list(outer_point_list, new_points, area_id)
                    except SyntaxError as err:
                        logging.error(err)
                        return None

        if len(outer_point_list) == 0:
            return None

        if outer_point_list[0] != outer_point_list[-1]:
            logging.warning("The outer boundary of area %d is not closed.", area_id)

        inner_point_list = [[]]
        inner_idx = 0
        for line_id in line_ids["inner"]:
            if len(inner_point_list[inner_idx]) == 0:
                if map_.roadlines.get(line_id):
                    inner_point_list[inner_idx] = list(map_.roadlines[line_id].geometry.coords)
            else:
                if map_.roadlines.get(line_id):
                    new_points = list(map_.roadlines[line_id].geometry.coords)
                    try:
                        self._append_point_list(inner_point_list[inner_idx], new_points, area_id)
                    except SyntaxError as err:
                        logging.error(err)
                        return None

            if inner_point_list[inner_idx][0] == inner_point_list[inner_idx][-1]:
                inner_point_list.append([])
                inner_idx += 1
        if len(inner_point_list[-1]) == 0:
            del inner_point_list[-1]
        elif inner_point_list[-1][0] != inner_point_list[-1][-1]:
            logging.warning("The inner boundary of area %d is not closed.", area_id)
        polygon = Polygon(outer_point_list, inner_point_list)

        area_tags = self._get_lanelet2_tags(xml_node)

        return Area(area_id, polygon, line_ids, set(regulatory_ids), **area_tags)

    def _parse_bounds_no_proj(self, xml_node: ET.Element) -> tuple:
        """Parse the map boundary without coordinate projection.

        Args:
            xml_node (ET.Element): The XML node of the boundary.

        Returns:
            tuple: The boundary expressed as (min_lon, max_lon, min_lat, max_lat),
                or None if any boundary value is missing.
        """
        min_lon = float(xml_node.get("minlon"))
        max_lon = float(xml_node.get("maxlon"))
        min_lat = float(xml_node.get("minlat"))
        max_lat = float(xml_node.get("maxlat"))

        if None not in [min_lon, max_lon, min_lat, max_lat]:
            return (min_lon, max_lon, min_lat, max_lat)

        return None

    def _parse_bounds(self, xml_node: ET.Element, projector: Proj, origin: tuple) -> tuple:
        """Parse the map boundary with coordinate projection.

        Args:
            xml_node (ET.Element): The XML node of the boundary.
            projector (Proj): The projection rule of the map.
            origin (tuple): The origin of the GPS coordinates.

        Returns:
            tuple: The boundary expressed as (min_x, max_x, min_y, max_y) in metres,
                or None if any boundary value is missing.
        """
        min_lon = float(xml_node.get("minlon"))
        max_lon = float(xml_node.get("maxlon"))
        min_lat = float(xml_node.get("minlat"))
        max_lat = float(xml_node.get("maxlat"))

        if None not in [min_lat, max_lat, min_lon, max_lon]:
            min_x, min_y = projector(min_lon, min_lat)
            max_x, max_y = projector(max_lon, max_lat)
            return (min_x - origin[0], max_x - origin[0], min_y - origin[1], max_y - origin[1])

        return None

    def _parse_nodes_no_proj(self, xml_node: ET.Element, lat0: float, lon0: float) -> Node:
        """Parse a node using equirectangular projection from the given origin.

        Converts geographic coordinates (lon, lat) to local metric coordinates
        (x, y) in metres using a simple equirectangular approximation.

        Args:
            xml_node (ET.Element): The XML node of the node.
            lat0 (float): Origin latitude in degrees.
            lon0 (float): Origin longitude in degrees.

        Returns:
            Node: A node with x-y coordinates in metres.
        """
        node_id = int(xml_node.attrib["id"])
        lon = float(xml_node.attrib["lon"])
        lat = float(xml_node.attrib["lat"])
        x = (lon - lon0) * 111320.0 * math.cos(math.radians(lat0))
        y = (lat - lat0) * 110540.0
        return Node(id_=node_id, x=x, y=y)

    def _parse_nodes(self, xml_node: ET.Element, projector: Proj, origin: tuple) -> Node:
        """Parse a node with coordinate projection.

        Args:
            xml_node (ET.Element): The XML node of the node.
            projector (Proj): The projection rule of the map.
            origin (tuple): The origin of the GPS coordinates.

        Returns:
            Node: A node with projected x-y coordinates in metres.
        """
        node_id = int(xml_node.attrib["id"])
        x, y = projector(xml_node.attrib["lon"], xml_node.attrib["lat"])

        return Node(id_=node_id, x=x - origin[0], y=y - origin[1])

    def _parse_way(self, xml_node: ET.Element, map_: Map) -> Area | RoadLine:
        """Parse an OSM way element as either an Area or a RoadLine.

        Args:
            xml_node (ET.Element): The XML node of the way.
            map_ (Map): The map that the road element belongs to.

        Returns:
            Area | RoadLine: An Area if the way is closed or tagged as area,
                otherwise a RoadLine.
        """
        id_ = self._mapped_way_id(int(xml_node.attrib["id"]))
        point_list = []
        point_ids = []

        for node in xml_node.findall("nd"):
            node_id = int(node.attrib["ref"])
            point_list.append(map_.nodes[node_id].location)
            point_ids.append(node_id)

        tags = self._get_tags(xml_node)
        is_area = tags.pop("area", False)

        if is_area or point_ids[0] == point_ids[-1]:
            road_element = Area(id_, Polygon(point_list), custom_tags=tags)
        else:
            road_element = RoadLine(id_, LineString(point_list), custom_tags=tags)

        return road_element

    def _parse_relation(self, xml_node: ET.Element, map_: Map) -> Area | RoadLine | Regulatory:
        """Parse an OSM relation element as an Area, RoadLine, or Regulatory.

        Args:
            xml_node (ET.Element): The XML node of the relation.
            map_ (Map): The map that the road element belongs to.

        Returns:
            Area | RoadLine | Regulatory: The parsed road element, or None if parsing fails.
        """
        id_ = self._mapped_relation_id(int(xml_node.attrib["id"]))
        tags = self._get_tags(xml_node)
        type_ = tags.pop("type")
        road_element = None

        if type_ == "multipolygon":
            road_element = self._parse_area(xml_node, map_)

        elif type_ == "route":
            line_ids = []
            for member in xml_node.findall("member"):
                if member.attrib["type"] == "way":
                    line_ids.append(self._mapped_way_id(int(member.attrib["ref"])))
            segments = [
                list(map_.roadlines[line_id].geometry.coords)
                for line_id in line_ids
                if map_.roadlines.get(line_id)
            ]
            point_list = self._stitch_polylines(segments, id_)
            road_element = RoadLine(id_, LineString(point_list), type_="route", custom_tags=tags)

        elif type_ == "restriction":
            subtype = tags.pop("restriction")
            froms = {}
            tos = {}
            vias = {}
            for member in xml_node.findall("member"):
                member_id = int(member.attrib["ref"])
                if member.attrib["type"] == "way":
                    member_id = self._mapped_way_id(member_id)
                elif member.attrib["type"] == "relation":
                    member_id = self._mapped_relation_id(member_id)
                if member.attrib["role"] == "from":
                    froms[member_id] = member.attrib["type"]
                elif member.attrib["role"] == "to":
                    tos[member_id] = member.attrib["type"]
                elif member.attrib["role"] == "via":
                    vias[member_id] = member.attrib["type"]

            tags["froms"] = froms
            tags["tos"] = tos
            tags["vias"] = vias
            road_element = Regulatory(id_, type_="restriction", subtype=subtype, custom_tags=tags)

        return road_element

    def _parse_roadline_lanelet2(self, xml_node: ET.Element, map_: Map) -> RoadLine:
        """Parse a Lanelet2 roadline from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the roadline.
            map_ (Map): The map that the roadline belongs to.

        Returns:
            RoadLine: A roadline with Lanelet2 tags.
        """
        line_id = self._mapped_way_id(int(xml_node.attrib["id"]))
        point_list = []

        for node in xml_node.findall("nd"):
            node_id = int(node.attrib["ref"])
            if node_id not in map_.nodes:
                logging.warning("Way %s references missing node %s; skipped it.", line_id, node_id)
                continue
            point_list.append(map_.nodes[node_id].location)
        if len(point_list) < 2:
            raise SyntaxError(f"Way {line_id} has fewer than 2 resolvable nodes.")
        linestring = LineString(point_list)

        tags = self._get_lanelet2_tags(xml_node)

        return RoadLine(id_=line_id, geometry=linestring, **tags)

    def _parse_lane_lanelet2(self, xml_node: ET.Element, map_: Map) -> Lane:
        """Parse a Lanelet2 lane from an XML relation node.

        Args:
            xml_node (ET.Element): The XML node of the lanelet relation.
            map_ (Map): The map that the lane belongs to.

        Returns:
            Lane: A lane with Lanelet2 tags and aligned left/right boundaries.
        """
        lane_id = self._mapped_relation_id(int(xml_node.attrib["id"]))
        line_ids = dict(left=[], right=[])
        regulatory_ids = []

        for member in xml_node.findall("member"):
            member_id = int(member.attrib["ref"])
            if member.attrib["role"] == "left":
                line_ids["left"].append(self._mapped_way_id(member_id))
            elif member.attrib["role"] == "right":
                line_ids["right"].append(self._mapped_way_id(member_id))
            elif member.attrib["role"] == "regulatory_element":
                regulatory_ids.append(self._mapped_relation_id(member_id))

        point_list = {}
        for side in ["left", "right"]:
            segments = [
                list(map_.roadlines[line_id].geometry.coords) for line_id in line_ids[side]
            ]
            point_list[side] = self._stitch_polylines(segments, lane_id)
            if len(point_list[side]) < 2:
                raise SyntaxError(f"Lane {lane_id} has no usable {side} boundary.")

        left_side = LineString(point_list["left"])
        right_side = LineString(point_list["right"])

        left_parallel = left_side.parallel_offset(0.1, "left")
        if left_side.hausdorff_distance(right_side) > left_parallel.hausdorff_distance(right_side):
            point_list["left"].reverse()
            left_side = LineString(point_list["left"])
        right_parallel = right_side.parallel_offset(0.1, "right")
        if right_side.hausdorff_distance(left_side) > right_parallel.hausdorff_distance(left_side):
            point_list["right"].reverse()
            right_side = LineString(point_list["right"])

        if left_side.crosses(right_side):
            logging.warning("The sides of lane %d is intersected.", lane_id)

        lane_tags = self._get_lanelet2_tags(xml_node)

        return Lane(
            id_=lane_id,
            left_side=left_side,
            right_side=right_side,
            line_ids=line_ids,
            regulatory_ids=set(regulatory_ids),
            **lane_tags,
        )

    def _parse_area_lanelet2(self, xml_node: ET.Element, map_: Map) -> Area:
        """Parse a Lanelet2 area from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the area.
            map_ (Map): The map that the area belongs to.

        Returns:
            Area: An area with Lanelet2 tags.
        """
        area_id = self._mapped_relation_id(int(xml_node.attrib["id"]))
        line_ids = dict(inner=[], outer=[])
        regulatory_ids = []

        for member in xml_node.findall("member"):
            member_id = int(member.attrib["ref"])
            if member.attrib["role"] == "outer":
                line_ids["outer"].append(self._mapped_way_id(member_id))
            elif member.attrib["role"] == "inner":
                line_ids["inner"].append(self._mapped_way_id(member_id))
            elif member.attrib["role"] == "regulatory_element":
                regulatory_ids.append(self._mapped_relation_id(member_id))

        outer_segments = [
            list(map_.roadlines[line_id].geometry.coords) for line_id in line_ids["outer"]
        ]
        outer_point_list = self._stitch_polylines(outer_segments, area_id)
        if outer_point_list[0] != outer_point_list[-1]:
            logging.warning("The outer boundary of area %d is not closed.", area_id)

        inner_point_list = [[]]
        inner_idx = 0
        for line_id in line_ids["inner"]:
            if len(inner_point_list[inner_idx]) == 0:
                inner_point_list[inner_idx] = list(map_.roadlines[line_id].geometry.coords)
            else:
                new_points = list(map_.roadlines[line_id].geometry.coords)
                self._append_point_list(inner_point_list[inner_idx], new_points, area_id)
            if inner_point_list[inner_idx][0] == inner_point_list[inner_idx][-1]:
                inner_point_list.append([])
                inner_idx += 1
        if len(inner_point_list[-1]) == 0:
            del inner_point_list[-1]
        elif inner_point_list[-1][0] != inner_point_list[-1][-1]:
            logging.warning("The inner boundary of area %d is not closed.", area_id)
        polygon = Polygon(outer_point_list, inner_point_list)

        area_tags = self._get_lanelet2_tags(xml_node)

        return Area(area_id, polygon, line_ids, set(regulatory_ids), **area_tags)

    def _parse_regulatory_lanelet2(self, xml_node: ET.Element) -> Regulatory:
        """Parse a Lanelet2 regulatory element from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the regulatory element.

        Returns:
            Regulatory: A regulatory element with Lanelet2 tags.
        """
        regulatory_id = self._mapped_relation_id(int(xml_node.attrib["id"]))
        relations = {}
        ways = {}
        for member in xml_node.findall("member"):
            if member.attrib["type"] == "relation":
                relations[self._mapped_relation_id(int(member.attrib["ref"]))] = member.attrib[
                    "role"
                ]
            elif member.attrib["type"] == "way":
                ways[self._mapped_way_id(int(member.attrib["ref"]))] = member.attrib["role"]

        regulatory_tags = self._get_lanelet2_tags(xml_node)
        if "speed_limit" in regulatory_tags:
            regulatory_tags["custom_tags"]["speed_limit"] = regulatory_tags.pop("speed_limit")

        return Regulatory(regulatory_id, relations, ways, **regulatory_tags)

    def parse(self, file_path: str, configs: dict = None) -> Map:
        """Parse an OpenStreetMap file into a Tactics2D Map.

        Args:
            file_path (str): The absolute path of the `.osm` file.
            configs (dict): Optional configuration dictionary with keys:
                project_rule (dict): Projection parameters passed to pyproj.Proj.
                gps_origin (tuple): GPS origin coordinates for projection.
                name (str): Map name.
                scenario_type (str): Scenario type.
                country (str): Country code.

        Returns:
            Map: A Tactics2D Map populated with all elements parsed from the OSM file.
        """
        xml_root = ET.parse(file_path).getroot()
        self._build_id_remaps(xml_root)

        if configs is not None:
            project_rule = configs.get("project_rule", None)
            gps_origin = configs.get("gps_origin", None)
        else:
            project_rule = None
            gps_origin = None

        projector = Proj(**project_rule) if project_rule else None
        to_project = None not in [projector, gps_origin]

        if to_project:
            origin = projector(*gps_origin)

        if configs is None:
            map_ = Map()
        else:
            map_ = Map(
                name=configs.get("name"),
                scenario_type=configs.get("scenario_type"),
                country=configs.get("country"),
            )

        node_boundary = xml_root.find("bounds")
        if node_boundary is not None:
            map_.set_boundary(
                self._parse_bounds(node_boundary, projector, origin)
                if to_project
                else self._parse_bounds_no_proj(node_boundary)
            )

        if to_project:
            for xml_node in xml_root.findall("node"):
                if xml_node.get("action") == "delete":
                    continue
                map_.add_node(self._parse_nodes(xml_node, projector, origin))
        else:
            all_nodes = [n for n in xml_root.findall("node") if n.get("action") != "delete"]
            if all_nodes:
                lat0 = float(all_nodes[0].attrib["lat"])
                lon0 = float(all_nodes[0].attrib["lon"])
            else:
                lat0, lon0 = 0.0, 0.0

            for xml_node in all_nodes:
                map_.add_node(self._parse_nodes_no_proj(xml_node, lat0, lon0))

        # A single malformed element (missing node reference, empty member
        # list, degenerate geometry) degrades to a warning instead of
        # aborting the whole map.
        recoverable_errors = (KeyError, IndexError, ValueError, SyntaxError)

        if self.lanelet2:
            for xml_node in xml_root.findall("way"):
                if xml_node.get("action") == "delete":
                    continue
                try:
                    map_.add_roadline(self._parse_roadline_lanelet2(xml_node, map_))
                except recoverable_errors as error:
                    logging.warning(
                        "Skipping way %s: %s", xml_node.attrib.get("id"), error
                    )

            for xml_node in xml_root.findall("relation"):
                if xml_node.get("action") == "delete":
                    continue
                for tag in xml_node.findall("tag"):
                    try:
                        if tag.attrib["v"] == "lanelet":
                            map_.add_lane(self._parse_lane_lanelet2(xml_node, map_))
                        elif tag.attrib["v"] in ["multipolygon", "area"]:
                            map_.add_area(self._parse_area_lanelet2(xml_node, map_))
                    except recoverable_errors as error:
                        logging.warning(
                            "Skipping relation %s: %s", xml_node.attrib.get("id"), error
                        )

            for xml_node in xml_root.findall("relation"):
                if xml_node.get("action") == "delete":
                    continue
                for tag in xml_node.findall("tag"):
                    if tag.attrib["v"] == "regulatory_element":
                        try:
                            map_.add_regulatory(self._parse_regulatory_lanelet2(xml_node))
                        except recoverable_errors as error:
                            logging.warning(
                                "Skipping relation %s: %s", xml_node.attrib.get("id"), error
                            )

        else:
            for xml_node in xml_root.findall("way"):
                if xml_node.get("action") == "delete":
                    continue
                try:
                    road_element = self._parse_way(xml_node, map_)
                except recoverable_errors as error:
                    logging.warning("Skipping way %s: %s", xml_node.attrib.get("id"), error)
                    continue

                if isinstance(road_element, RoadLine):
                    map_.add_roadline(road_element)
                elif isinstance(road_element, Area):
                    map_.add_area(road_element)

            for xml_node in xml_root.findall("relation"):
                if xml_node.get("action") == "delete":
                    continue
                try:
                    road_element = self._parse_relation(xml_node, map_)
                except recoverable_errors as error:
                    logging.warning(
                        "Skipping relation %s: %s", xml_node.attrib.get("id"), error
                    )
                    continue

                if isinstance(road_element, RoadLine):
                    map_.add_roadline(road_element)
                elif isinstance(road_element, Area):
                    map_.add_area(road_element)
                elif isinstance(road_element, Regulatory):
                    map_.add_regulatory(road_element)

        return map_
