# Copyright (C) 2026, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""Parser for SUMO network (.net.xml) files."""

from __future__ import annotations

import logging
import math
import os

import defusedxml.ElementTree as ET
from shapely.geometry import LineString, MultiPoint

from tactics2d.map.element import Junction, Lane, Map, RoadLine


class NetXMLParser:
    """Parser for the SUMO network format (.net.xml) map.

    Reads a SUMO road-network file and converts it into a Tactics2D Map object
    containing lanes, road-mark lines, junctions, and connections. The parser
    operates directly on the XML without any external SUMO dependency.

    Lanes are constructed from the centre-line shape attribute: left and right
    boundaries are generated by applying a constant-width normal offset to each
    vertex, guaranteeing that both boundaries share the same point order and
    orientation. Internal edges (function="internal") are included so that
    junction connector geometry is preserved.

    Reference:
        https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html
    """

    _LANE_TYPE_DICT: dict[str, str] = {
        "highway.motorway": "highway",
        "highway.trunk": "highway",
        "highway.primary": "road",
        "highway.secondary": "road",
        "highway.tertiary": "road",
        "highway.residential": "road",
        "highway.service": "road",
        "highway.pedestrian": "walkway",
        "highway.footway": "walkway",
        "highway.cycleway": "bicycle_lane",
        "railway.rail": "rail",
        "railway.tram": "tram",
    }

    _DEFAULT_LANE_WIDTH: float = 3.2

    def __init__(self) -> None:
        self._id_counter: int = 0

    def parse(self, file_path: str) -> Map:
        """Parse a SUMO network file (.net.xml) into a Tactics2D Map.

        Args:
            file_path: Absolute or relative path to the .net.xml file.

        Returns:
            A Tactics2D Map populated with lanes, roadlines, junctions, and
            connections.
        """
        self._id_counter = 0

        xml_root = ET.parse(file_path).getroot()
        map_name = os.path.splitext(os.path.basename(file_path))[0]
        map_ = Map(name=map_name)

        self._parse_location(xml_root, map_)
        edge_to_junction = self._build_edge_junction_map(xml_root)
        self._parse_edges(xml_root, map_)
        sumo_to_tactics = self._parse_junctions(xml_root, map_)
        self._parse_connections(xml_root, map_, edge_to_junction, sumo_to_tactics)
        self._compute_junction_shapes(map_, edge_to_junction, sumo_to_tactics)

        self._id_counter = 0
        return map_

    @staticmethod
    def parse_shape(shape_str: str) -> list[tuple[float, float]]:
        """Parse a SUMO shape string into a list of (x, y) coordinate tuples.

        Args:
            shape_str: Space-separated coordinate pairs,
                e.g. "0.00,1.00 2.00,3.00".

        Returns:
            List of (x, y) tuples parsed from the shape string.
        """
        points: list[tuple[float, float]] = []
        for pair in shape_str.strip().split():
            parts = pair.split(",")
            if len(parts) >= 2:
                points.append((float(parts[0]), float(parts[1])))
        return points

    @staticmethod
    def offset_line(
        coords: list[tuple[float, float]], half_width: float
    ) -> tuple[list[tuple[float, float]], list[tuple[float, float]]]:
        """Create left and right boundary polylines by offsetting a centre-line.

        For each vertex the normal vector pointing to the left (when travelling
        from start to end) is computed, and both the left and right offset
        points are calculated.

        Args:
            coords: Centre-line coordinates [(x0, y0), (x1, y1), ...].
            half_width: Half of the lane width in metres.

        Returns:
            A tuple (left_coords, right_coords), each a list of (x, y) tuples
            with the same number of points as the centre-line.
        """
        left_coords: list[tuple[float, float]] = []
        right_coords: list[tuple[float, float]] = []
        n = len(coords)
        if n < 2:
            return left_coords, right_coords

        last_nx: float = 0.0
        last_ny: float = 1.0

        for i in range(n):
            if i == 0:
                dx = coords[1][0] - coords[0][0]
                dy = coords[1][1] - coords[0][1]
            elif i == n - 1:
                dx = coords[-1][0] - coords[-2][0]
                dy = coords[-1][1] - coords[-2][1]
            else:
                dx = coords[i + 1][0] - coords[i - 1][0]
                dy = coords[i + 1][1] - coords[i - 1][1]

            seg_len = math.hypot(dx, dy)
            if seg_len < 1e-12:
                nx = last_nx
                ny = last_ny
            else:
                nx = -dy / seg_len
                ny = dx / seg_len
                last_nx = nx
                last_ny = ny

            left_coords.append((coords[i][0] + nx * half_width, coords[i][1] + ny * half_width))
            right_coords.append((coords[i][0] - nx * half_width, coords[i][1] - ny * half_width))

        return left_coords, right_coords

    def get_lane_subtype(self, edge_type: str) -> str:
        """Map a SUMO edge type string to a Tactics2D lane subtype.

        Args:
            edge_type: The SUMO edge type attribute string.

        Returns:
            The corresponding Tactics2D lane subtype. Defaults to 'road'.
        """
        return self._LANE_TYPE_DICT.get(edge_type, "road")

    def _next_id(self) -> int:
        uid = self._id_counter
        self._id_counter += 1
        return uid

    def _resolve_half_width(self, lane_node, fallback_width: float | None = None) -> float:
        """Determine the half-width for a lane element.

        Priority: lane[@width] > fallback_width > _DEFAULT_LANE_WIDTH.
        """
        width_attr = lane_node.attrib.get("width")
        if width_attr is not None:
            try:
                val = float(width_attr)
                if val > 0:
                    return val / 2.0
            except ValueError:
                pass
        base = fallback_width if fallback_width is not None else self._DEFAULT_LANE_WIDTH
        return base / 2.0

    def _estimate_lane_width(self, lane_nodes: list) -> float:
        """Estimate lane width from spacing between adjacent lane shapes."""
        if len(lane_nodes) < 2:
            return self._DEFAULT_LANE_WIDTH
        try:
            shape0 = self.parse_shape(lane_nodes[0].attrib.get("shape", ""))
            shape1 = self.parse_shape(lane_nodes[1].attrib.get("shape", ""))
            if shape0 and shape1:
                dx = shape1[0][0] - shape0[0][0]
                dy = shape1[0][1] - shape0[0][1]
                computed = math.hypot(dx, dy)
                if 1.5 < computed < 6.0:
                    return computed
        except Exception:
            pass
        return self._DEFAULT_LANE_WIDTH

    def _load_lane(
        self, lane_node, edge_type: str, lane_width: float | None = None
    ) -> tuple[Lane | None, RoadLine | None, RoadLine | None]:
        """Parse one SUMO <lane> element into a Lane and its boundary RoadLines.

        Returns:
            A tuple (lane, left_line, right_line). All None when parsing fails.
        """
        shape_str = lane_node.attrib.get("shape", "")
        if not shape_str:
            return None, None, None

        coords = self.parse_shape(shape_str)
        if len(coords) < 2:
            return None, None, None

        speed_ms = float(lane_node.attrib.get("speed", "13.89"))
        half_width = self._resolve_half_width(lane_node, lane_width)
        left_coords, right_coords = self.offset_line(coords, half_width)

        left_geom = LineString(left_coords)
        right_geom = LineString(right_coords)

        left_id = self._next_id()
        right_id = self._next_id()
        lane_id = self._next_id()
        lane_sumo_id = lane_node.attrib.get("id", "")

        left_line = RoadLine(id_=left_id, geometry=left_geom, type_="line_thin", subtype="dashed")
        right_line = RoadLine(
            id_=right_id, geometry=right_geom, type_="line_thin", subtype="dashed"
        )
        lane = Lane(
            id_=lane_id,
            left_side=left_geom,
            right_side=right_geom,
            subtype=self.get_lane_subtype(edge_type),
            line_ids={"left": [left_id], "right": [right_id]},
            speed_limit=round(speed_ms * 3.6, 3),
            speed_limit_unit="km/h",
            custom_tags={"sumo_id": lane_sumo_id, "centerline": coords},
        )
        return lane, left_line, right_line

    def _load_junction(self, junction_node) -> Junction:
        """Parse a SUMO <junction> element into a Junction object."""
        shape_str = junction_node.attrib.get("shape", "")
        shape_pts = self.parse_shape(shape_str) if shape_str else []
        return Junction(
            id_=self._next_id(),
            custom_tags={
                "sumo_id": junction_node.attrib.get("id", ""),
                "x": junction_node.attrib.get("x", ""),
                "y": junction_node.attrib.get("y", ""),
                "type": junction_node.attrib.get("type", ""),
                "shape": shape_pts,
            },
        )

    def _load_connection(self, conn_node) -> Junction:
        """Parse a SUMO <connection> element into a Junction object."""
        return Junction(
            id_=self._next_id(),
            custom_tags={
                "from_edge": conn_node.attrib.get("from", ""),
                "to_edge": conn_node.attrib.get("to", ""),
                "from_lane": conn_node.attrib.get("fromLane", ""),
                "to_lane": conn_node.attrib.get("toLane", ""),
                "via": conn_node.attrib.get("via", ""),
                "dir": conn_node.attrib.get("dir", ""),
                "state": conn_node.attrib.get("state", ""),
            },
        )

    def _parse_location(self, xml_root, map_: Map) -> None:
        """Parse <location> and set map boundary if valid."""
        location_node = xml_root.find("location")
        if location_node is None:
            return
        boundary_str = location_node.attrib.get("convBoundary", "")
        if not boundary_str:
            return
        parts = boundary_str.split(",")
        if len(parts) != 4:
            return
        x_min, y_min, x_max, y_max = (float(v) for v in parts)
        if x_max > x_min and y_max > y_min:
            map_.set_boundary((x_min, x_max, y_min, y_max))

    def _build_edge_junction_map(self, xml_root) -> dict[str, str]:
        """Build mapping from non-internal edge id to destination junction."""
        edge_to_junction: dict[str, str] = {}
        for edge_node in xml_root.findall("edge"):
            if edge_node.attrib.get("function") == "internal":
                continue
            edge_id = edge_node.attrib.get("id", "")
            to_node = edge_node.attrib.get("to", "")
            if edge_id and to_node:
                edge_to_junction[edge_id] = to_node
        return edge_to_junction

    def _parse_edges(self, xml_root, map_: Map) -> None:
        """Parse all <edge> elements (including internal) and add lanes to map."""
        uturn_lanes: set[str] = set()
        for conn_node in xml_root.findall("connection"):
            if conn_node.attrib.get("dir") == "T":
                via = conn_node.attrib.get("via", "")
                if via:
                    uturn_lanes.add(via)

        for edge_node in xml_root.findall("edge"):
            edge_type = edge_node.attrib.get("type", "")
            edge_from = edge_node.attrib.get("from", "")
            edge_to = edge_node.attrib.get("to", "")
            is_internal = edge_node.attrib.get("function") == "internal"
            lane_nodes = edge_node.findall("lane")

            lane_width = self._estimate_lane_width(lane_nodes)

            for lane_node in lane_nodes:
                try:
                    lane_sumo_id = lane_node.attrib.get("id", "")

                    # Skip U-turn internal lanes (dir="T" in connections).
                    # These have extreme curvature that causes offset_line to
                    # collapse the inner boundary, rendering as a dot.
                    if is_internal and lane_sumo_id in uturn_lanes:
                        continue

                    lane, left_line, right_line = self._load_lane(lane_node, edge_type, lane_width)
                    if lane is None:
                        continue
                    lane.custom_tags["from_node"] = edge_from
                    lane.custom_tags["to_node"] = edge_to
                    lane.custom_tags["is_internal"] = is_internal
                    map_.add_lane(lane)
                    map_.add_roadline(left_line)
                    map_.add_roadline(right_line)
                except Exception as exc:
                    logging.warning(
                        "Failed to parse lane %s: %s", lane_node.attrib.get("id", "unknown"), exc
                    )

    def _parse_junctions(self, xml_root, map_: Map) -> dict[str, int]:
        """Parse <junction> elements, skipping only dead_end types.

        All non-dead_end junctions are added to the map for topological
        completeness. Junctions without a valid shape will not be rendered
        (the rendering layer checks shape length before drawing).

        Returns:
            Mapping from sumo_junction_id to tactics2d_junction_id.
        """
        _SKIP_TYPES = {"dead_end"}
        sumo_to_tactics: dict[str, int] = {}

        for junction_node in xml_root.findall("junction"):
            junc_type = junction_node.attrib.get("type", "")
            if junc_type in _SKIP_TYPES:
                continue

            try:
                junction = self._load_junction(junction_node)
                map_.add_junction(junction)
                sumo_id = junction_node.attrib.get("id", "")
                if sumo_id:
                    sumo_to_tactics[sumo_id] = junction.id_
            except Exception as exc:
                logging.warning(
                    "Failed to parse junction %s: %s",
                    junction_node.attrib.get("id", "unknown"),
                    exc,
                )
        return sumo_to_tactics

    def _parse_connections(
        self, xml_root, map_: Map, edge_to_junction: dict[str, str], sumo_to_tactics: dict[str, int]
    ) -> None:
        """Parse <connection> elements and attach them to their junctions."""
        for conn_node in xml_root.findall("connection"):
            try:
                connection = self._load_connection(conn_node)
                from_edge = connection.custom_tags.get("from_edge", "")
                sumo_junc_id = edge_to_junction.get(from_edge, "")
                tactics_id = sumo_to_tactics.get(sumo_junc_id)
                if tactics_id is not None and tactics_id in map_.junctions:
                    map_.junctions[tactics_id].add_connection(connection)
                else:
                    logging.debug(
                        "Cannot find junction for connection from_edge=%s; " "skipping.", from_edge
                    )
            except Exception as exc:
                logging.warning("Failed to parse connection: %s", exc)

    def _compute_junction_shapes(
        self, map_: Map, edge_to_junction: dict[str, str], sumo_to_tactics: dict[str, int]
    ) -> None:
        """Compute convex-hull shapes for junctions that lack explicit shape.

        Collects lane boundary endpoints that terminate at each junction and
        computes a convex hull to approximate the junction polygon. Only
        junctions with an empty shape list are processed.
        """
        junction_endpoints: dict[str, list[tuple[float, float]]] = {
            sumo_id: [] for sumo_id in sumo_to_tactics
        }

        for lane in map_.lanes.values():
            tags = lane.custom_tags or {}
            sumo_id = tags.get("sumo_id", "")
            if not sumo_id or "_" not in sumo_id:
                continue

            edge_id = sumo_id.rsplit("_", 1)[0]

            to_sumo = edge_to_junction.get(edge_id)
            if to_sumo and to_sumo in junction_endpoints:
                try:
                    for side in (lane.left_side, lane.right_side):
                        coords = list(side.coords)
                        junction_endpoints[to_sumo].append(coords[-1])
                except Exception:
                    pass

            if tags.get("is_internal"):
                parent_junc = tags.get("from_node", "")
                if parent_junc and parent_junc in junction_endpoints:
                    try:
                        for side in (lane.left_side, lane.right_side):
                            coords = list(side.coords)
                            junction_endpoints[parent_junc].append(coords[0])
                            junction_endpoints[parent_junc].append(coords[-1])
                    except Exception:
                        pass

        for sumo_id, tactics_id in sumo_to_tactics.items():
            junction = map_.junctions.get(tactics_id)
            if junction is None:
                continue
            if junction.custom_tags.get("shape"):
                continue

            pts = junction_endpoints.get(sumo_id, [])
            if len(pts) < 3:
                continue

            try:
                hull = MultiPoint(pts).convex_hull
                if hull.geom_type == "Polygon" and not hull.is_empty:
                    junction.custom_tags["shape"] = list(hull.exterior.coords)
            except Exception as exc:
                logging.warning("Failed to compute convex hull for junction %s: %s", sumo_id, exc)
