# Copyright (C) 2024, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""OSM parser implementation."""

from __future__ import annotations

import logging
import math

import defusedxml.ElementTree as ET
from pyproj import Proj
from shapely.geometry import LineString, Polygon

from tactics2d.map.element import Area, Lane, Map, Node, Regulatory, RoadLine


class OSMParser:
    """This class implements a parser for the original OpenStreetMap format map. The parser is tested with data generated by the official OpenStreetMap website and the JOSM software application.

    Example:
        >>> parser = OSMParser()
        >>> map_ = parser.parse("/path/to/map.osm")
        >>> parser_l2 = OSMParser(lanelet2=True)
        >>> map_l2 = parser_l2.parse("/path/to/map_lanelet2.osm")
    """

    def __init__(self, lanelet2: bool = False):
        """Initialize the parser.

        Args:
            lanelet2 (bool): Whether the `.osm` file is annotated in Lanelet2 format.
                Defaults to False.
        """
        self.lanelet2 = lanelet2

    def _append_point_list(self, point_list: list, new_points: list, component_id: int) -> None:
        """Append new points to an existing point list, handling direction alignment.

        Args:
            point_list (list): Existing list of points to append to.
            new_points (list): New points to append.
            component_id (int): The id of the component, used for error messages.

        Raises:
            SyntaxError: If the points are not continuous.
        """
        if point_list[-1] == new_points[0]:
            pass
        elif point_list[0] == new_points[0]:
            point_list.reverse()
        elif point_list[0] == new_points[-1]:
            point_list.reverse()
            new_points.reverse()
        elif point_list[-1] == new_points[-1]:
            new_points.reverse()
        else:
            raise SyntaxError(f"Points on the side of relation {component_id} is not continuous.")

        point_list += new_points[1:]

    def _get_tags(self, xml_node: ET.Element) -> dict:
        """Parse OSM tags from an XML node into a dictionary.

        Args:
            xml_node (ET.Element): The XML node containing tag elements.

        Returns:
            dict: Parsed tags with boolean conversion for area and oneway keys.
        """
        tags = {}
        bool_tags = {"area", "oneway"}

        for tag in xml_node.findall("tag"):
            if tag.attrib["k"] in bool_tags:
                tags[tag.attrib["k"]] = tag.attrib["v"] == "yes"
            else:
                tags[tag.attrib["k"]] = tag.attrib["v"]

        return tags

    def _get_lanelet2_tags(self, xml_node: ET.Element) -> dict:
        """Parse Lanelet2 tags from an XML node into a structured dictionary.

        Args:
            xml_node (ET.Element): The XML node containing Lanelet2 tag elements.

        Returns:
            dict: Parsed tags with type conversion for speed_limit and boolean
                conversion for bool_tags. Lane change attributes are stored as
                tuples in custom_tags.
        """
        tags = {}
        tags["custom_tags"] = {}

        directly_save = {
            "subtype",
            "color",
            "width",
            "location",
            "inferred_participants",
            "speed_limit",
        }
        bool_tags = {"temporary", "speed_limit_mandatory", "dynamic", "fallback", "oneway"}

        for tag in xml_node.findall("tag"):
            if tag.attrib["k"] == "type":
                tags["type_"] = tag.attrib["v"]

            elif tag.attrib["k"] in directly_save:
                if tag.attrib["k"] == "speed_limit":
                    try:
                        tags["speed_limit"] = float(tag.attrib["v"])
                    except (ValueError, TypeError):
                        logging.warning("Invalid speed_limit value: %s", tag.attrib["v"])
                else:
                    tags[tag.attrib["k"]] = tag.attrib["v"]

            elif tag.attrib["k"] in bool_tags:
                tags["custom_tags"][tag.attrib["k"]] = tag.attrib["v"] == "yes"

            elif "lane_change" in tag.attrib["k"]:
                if "lane_change" in tags["custom_tags"]:
                    raise SyntaxError("Conflict tags on lane changing property.")
                else:
                    if tag.attrib["k"] == "lane_change":
                        tags["custom_tags"]["lane_change"] = (
                            (True, True) if tag.attrib["v"] == "yes" else (False, False)
                        )
                    elif tag.attrib["k"] == "lane_change:left":
                        tags["custom_tags"]["lane_change"] = (
                            (True, False) if tag.attrib["v"] == "yes" else (False, False)
                        )
                    elif tag.attrib["k"] == "lane_change:right":
                        tags["custom_tags"]["lane_change"] = (
                            (False, True) if tag.attrib["v"] == "yes" else (False, False)
                        )

            else:
                tags["custom_tags"][tag.attrib["k"]] = tag.attrib["v"]

        return tags

    def _load_area(self, xml_node: ET.Element, map_: Map) -> Area:
        """Parse an OSM area element from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the area.
            map_ (Map): The map that the area belongs to.

        Returns:
            Area: The parsed area, or None if the outer boundary is empty or parsing fails.
        """
        area_id = int(xml_node.attrib["id"])
        line_ids = dict(inner=[], outer=[])
        regulatory_ids = []

        for member in xml_node.findall("member"):
            member_id = int(member.attrib["ref"])
            if member.attrib["role"] == "outer":
                line_ids["outer"].append(member_id)
            elif member.attrib["role"] == "inner":
                line_ids["inner"].append(member_id)
            elif member.attrib["role"] == "regulatory_element":
                regulatory_ids.append(member_id)

        outer_point_list = []
        for line_id in line_ids["outer"]:
            if len(outer_point_list) == 0:
                if map_.roadlines.get(line_id):
                    outer_point_list = list(map_.roadlines[line_id].geometry.coords)
            else:
                if map_.roadlines.get(line_id):
                    new_points = list(map_.roadlines[line_id].geometry.coords)
                    try:
                        self._append_point_list(outer_point_list, new_points, area_id)
                    except SyntaxError as err:
                        logging.error(err)
                        return None

        if len(outer_point_list) == 0:
            return None

        if outer_point_list[0] != outer_point_list[-1]:
            logging.warning("The outer boundary of area %d is not closed.", area_id)

        inner_point_list = [[]]
        inner_idx = 0
        for line_id in line_ids["inner"]:
            if len(inner_point_list[inner_idx]) == 0:
                if map_.roadlines.get(line_id):
                    inner_point_list[inner_idx] = list(map_.roadlines[line_id].geometry.coords)
            else:
                if map_.roadlines.get(line_id):
                    new_points = list(map_.roadlines[line_id].geometry.coords)
                    try:
                        self._append_point_list(inner_point_list[inner_idx], new_points, area_id)
                    except SyntaxError as err:
                        logging.error(err)
                        return None

            if inner_point_list[inner_idx][0] == inner_point_list[inner_idx][-1]:
                inner_point_list.append([])
                inner_idx += 1
        if len(inner_point_list[-1]) == 0:
            del inner_point_list[-1]
        elif inner_point_list[-1][0] != inner_point_list[-1][-1]:
            logging.warning("The inner boundary of area %d is not closed.", area_id)
        polygon = Polygon(outer_point_list, inner_point_list)

        area_tags = self._get_lanelet2_tags(xml_node)

        return Area(area_id, polygon, line_ids, set(regulatory_ids), **area_tags)

    def _load_bounds_no_proj(self, xml_node: ET.Element) -> tuple:
        """Load the map boundary without coordinate projection.

        Args:
            xml_node (ET.Element): The XML node of the boundary.

        Returns:
            tuple: The boundary expressed as (min_lon, max_lon, min_lat, max_lat),
                or None if any boundary value is missing.
        """
        min_lon = float(xml_node.get("minlon"))
        max_lon = float(xml_node.get("maxlon"))
        min_lat = float(xml_node.get("minlat"))
        max_lat = float(xml_node.get("maxlat"))

        if None not in [min_lon, max_lon, min_lat, max_lat]:
            return (min_lon, max_lon, min_lat, max_lat)

        return None

    def _load_bounds(self, xml_node: ET.Element, projector: Proj, origin: tuple) -> tuple:
        """Load the map boundary with coordinate projection.

        Args:
            xml_node (ET.Element): The XML node of the boundary.
            projector (Proj): The projection rule of the map.
            origin (tuple): The origin of the GPS coordinates.

        Returns:
            tuple: The boundary expressed as (min_x, max_x, min_y, max_y) in metres,
                or None if any boundary value is missing.
        """
        min_lon = float(xml_node.get("minlon"))
        max_lon = float(xml_node.get("maxlon"))
        min_lat = float(xml_node.get("minlat"))
        max_lat = float(xml_node.get("maxlat"))

        if None not in [min_lat, max_lat, min_lon, max_lon]:
            min_x, min_y = projector(min_lon, min_lat)
            max_x, max_y = projector(max_lon, max_lat)
            return (min_x - origin[0], max_x - origin[0], min_y - origin[1], max_y - origin[1])

        return None

    def _load_nodes_no_proj(self, xml_node: ET.Element, lat0: float, lon0: float) -> Node:
        """Load a node using equirectangular projection from the given origin.

        Converts geographic coordinates (lon, lat) to local metric coordinates
        (x, y) in metres using a simple equirectangular approximation.

        Args:
            xml_node (ET.Element): The XML node of the node.
            lat0 (float): Origin latitude in degrees.
            lon0 (float): Origin longitude in degrees.

        Returns:
            Node: A node with x-y coordinates in metres.
        """
        node_id = int(xml_node.attrib["id"])
        lon = float(xml_node.attrib["lon"])
        lat = float(xml_node.attrib["lat"])
        x = (lon - lon0) * 111320.0 * math.cos(math.radians(lat0))
        y = (lat - lat0) * 110540.0
        return Node(id_=node_id, x=x, y=y)

    def _load_nodes(self, xml_node: ET.Element, projector: Proj, origin: tuple) -> Node:
        """Load a node with coordinate projection.

        Args:
            xml_node (ET.Element): The XML node of the node.
            projector (Proj): The projection rule of the map.
            origin (tuple): The origin of the GPS coordinates.

        Returns:
            Node: A node with projected x-y coordinates in metres.
        """
        node_id = int(xml_node.attrib["id"])
        x, y = projector(xml_node.attrib["lon"], xml_node.attrib["lat"])

        return Node(id_=node_id, x=x - origin[0], y=y - origin[1])

    def _load_way(self, xml_node: ET.Element, map_: Map) -> Area | RoadLine:
        """Load an OSM way element as either an Area or a RoadLine.

        Args:
            xml_node (ET.Element): The XML node of the way.
            map_ (Map): The map that the road element belongs to.

        Returns:
            Area | RoadLine: An Area if the way is closed or tagged as area,
                otherwise a RoadLine.
        """
        id_ = int(xml_node.attrib["id"])
        point_list = []
        point_ids = []

        for node in xml_node.findall("nd"):
            node_id = int(node.attrib["ref"])
            point_list.append(map_.nodes[node_id].location)
            point_ids.append(node_id)

        tags = self._get_tags(xml_node)
        is_area = tags.pop("area", False)

        if is_area or point_ids[0] == point_ids[-1]:
            road_element = Area(id_, Polygon(point_list), custom_tags=tags)
        else:
            road_element = RoadLine(id_, LineString(point_list), custom_tags=tags)

        return road_element

    def _load_relation(self, xml_node: ET.Element, map_: Map) -> Area | RoadLine | Regulatory:
        """Load an OSM relation element as an Area, RoadLine, or Regulatory.

        Args:
            xml_node (ET.Element): The XML node of the relation.
            map_ (Map): The map that the road element belongs to.

        Returns:
            Area | RoadLine | Regulatory: The parsed road element, or None if parsing fails.
        """
        id_ = int(xml_node.attrib["id"])
        tags = self._get_tags(xml_node)
        type_ = tags.pop("type")
        road_element = None

        if type_ == "multipolygon":
            road_element = self._load_area(xml_node, map_)

        elif type_ == "route":
            point_list = []
            line_ids = []
            for member in xml_node.findall("member"):
                if member.attrib["type"] == "way":
                    line_ids.append(int(member.attrib["ref"]))
            for line_id in line_ids:
                if len(point_list) == 0:
                    if map_.roadlines.get(line_id):
                        point_list = list(map_.roadlines[line_id].geometry.coords)
                if map_.roadlines.get(line_id):
                    new_points = list(map_.roadlines[line_id].geometry.coords)
                    try:
                        self._append_point_list(point_list, new_points, id_)
                    except SyntaxError as err:
                        logging.error(err)
                        return None
            road_element = RoadLine(id_, LineString(point_list), type_="route", custom_tags=tags)

        elif type_ == "restriction":
            subtype = tags.pop("restriction")
            froms = {}
            tos = {}
            vias = {}
            for member in xml_node.findall("member"):
                member_id = int(member.attrib["ref"])
                if member.attrib["role"] == "from":
                    froms[member_id] = member.attrib["type"]
                elif member.attrib["role"] == "to":
                    tos[member_id] = member.attrib["type"]
                elif member.attrib["role"] == "via":
                    vias[member_id] = member.attrib["type"]

            tags["froms"] = froms
            tags["tos"] = tos
            tags["vias"] = vias
            road_element = Regulatory(id_, type_="restriction", subtype=subtype, custom_tags=tags)

        return road_element

    def _load_roadline_lanelet2(self, xml_node: ET.Element, map_: Map) -> RoadLine:
        """Load a Lanelet2 roadline from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the roadline.
            map_ (Map): The map that the roadline belongs to.

        Returns:
            RoadLine: A roadline with Lanelet2 tags.
        """
        line_id = int(xml_node.attrib["id"])
        point_list = []

        for node in xml_node.findall("nd"):
            point_list.append(map_.nodes[int(node.attrib["ref"])].location)
        linestring = LineString(point_list)

        tags = self._get_lanelet2_tags(xml_node)

        return RoadLine(id_=line_id, geometry=linestring, **tags)

    def _load_lane_lanelet2(self, xml_node: ET.Element, map_: Map) -> Lane:
        """Load a Lanelet2 lane from an XML relation node.

        Args:
            xml_node (ET.Element): The XML node of the lanelet relation.
            map_ (Map): The map that the lane belongs to.

        Returns:
            Lane: A lane with Lanelet2 tags and aligned left/right boundaries.
        """
        lane_id = int(xml_node.attrib["id"])
        line_ids = dict(left=[], right=[])
        regulatory_ids = []

        for member in xml_node.findall("member"):
            member_id = int(member.attrib["ref"])
            if member.attrib["role"] == "left":
                line_ids["left"].append(member_id)
            elif member.attrib["role"] == "right":
                line_ids["right"].append(member_id)
            elif member.attrib["role"] == "regulatory_element":
                regulatory_ids.append(member_id)

        point_list = {}
        for side in ["left", "right"]:
            point_list[side] = list(map_.roadlines[line_ids[side][0]].geometry.coords)
            for line_id in line_ids[side][1:]:
                new_nodes = list(map_.roadlines[line_id].geometry.coords)
                self._append_point_list(point_list[side], new_nodes, lane_id)

        left_side = LineString(point_list["left"])
        right_side = LineString(point_list["right"])

        left_parallel = left_side.parallel_offset(0.1, "left")
        if left_side.hausdorff_distance(right_side) > left_parallel.hausdorff_distance(right_side):
            point_list["left"].reverse()
            left_side = LineString(point_list["left"])
        right_parallel = right_side.parallel_offset(0.1, "right")
        if right_side.hausdorff_distance(left_side) > right_parallel.hausdorff_distance(left_side):
            point_list["right"].reverse()
            right_side = LineString(point_list["right"])

        if left_side.crosses(right_side):
            logging.warning("The sides of lane %d is intersected.", lane_id)

        lane_tags = self._get_lanelet2_tags(xml_node)

        return Lane(
            id_=lane_id,
            left_side=left_side,
            right_side=right_side,
            line_ids=line_ids,
            regulatory_ids=set(regulatory_ids),
            **lane_tags,
        )

    def _load_area_lanelet2(self, xml_node: ET.Element, map_: Map) -> Area:
        """Load a Lanelet2 area from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the area.
            map_ (Map): The map that the area belongs to.

        Returns:
            Area: An area with Lanelet2 tags.
        """
        area_id = int(xml_node.attrib["id"])
        line_ids = dict(inner=[], outer=[])
        regulatory_ids = []

        for member in xml_node.findall("member"):
            member_id = int(member.attrib["ref"])
            if member.attrib["role"] == "outer":
                line_ids["outer"].append(member_id)
            elif member.attrib["role"] == "inner":
                line_ids["inner"].append(member_id)
            elif member.attrib["role"] == "regulatory_element":
                regulatory_ids.append(member_id)

        outer_point_list = list(map_.roadlines[line_ids["outer"][0]].geometry.coords)
        for line_id in line_ids["outer"][1:]:
            new_points = list(map_.roadlines[line_id].geometry.coords)
            self._append_point_list(outer_point_list, new_points, area_id)
        if outer_point_list[0] != outer_point_list[-1]:
            logging.warning("The outer boundary of area %d is not closed.", area_id)

        inner_point_list = [[]]
        inner_idx = 0
        for line_id in line_ids["inner"]:
            if len(inner_point_list[inner_idx]) == 0:
                inner_point_list[inner_idx] = list(map_.roadlines[line_id].geometry.coords)
            else:
                new_points = list(map_.roadlines[line_id].geometry.coords)
                self._append_point_list(inner_point_list[inner_idx], new_points, area_id)
            if inner_point_list[inner_idx][0] == inner_point_list[inner_idx][-1]:
                inner_point_list.append([])
                inner_idx += 1
        if len(inner_point_list[-1]) == 0:
            del inner_point_list[-1]
        elif inner_point_list[-1][0] != inner_point_list[-1][-1]:
            logging.warning("The inner boundary of area %d is not closed.", area_id)
        polygon = Polygon(outer_point_list, inner_point_list)

        area_tags = self._get_lanelet2_tags(xml_node)

        return Area(area_id, polygon, line_ids, set(regulatory_ids), **area_tags)

    def _load_regulatory_lanelet2(self, xml_node: ET.Element) -> Regulatory:
        """Load a Lanelet2 regulatory element from an XML node.

        Args:
            xml_node (ET.Element): The XML node of the regulatory element.

        Returns:
            Regulatory: A regulatory element with Lanelet2 tags.
        """
        regulatory_id = int(xml_node.attrib["id"])
        relations = {}
        ways = {}
        for member in xml_node.findall("member"):
            if member.attrib["type"] == "relation":
                relations[int(member.attrib["ref"])] = member.attrib["role"]
            elif member.attrib["type"] == "way":
                ways[int(member.attrib["ref"])] = member.attrib["role"]

        regulatory_tags = self._get_lanelet2_tags(xml_node)
        if "speed_limit" in regulatory_tags:
            regulatory_tags["custom_tags"]["speed_limit"] = regulatory_tags.pop("speed_limit")

        return Regulatory(regulatory_id, relations, ways, **regulatory_tags)

    def parse(self, file_path: str, configs: dict = None) -> Map:
        """Parse an OpenStreetMap file into a Tactics2D Map.

        Args:
            file_path (str): The absolute path of the `.osm` file.
            configs (dict): Optional configuration dictionary with keys:
                project_rule (dict): Projection parameters passed to pyproj.Proj.
                gps_origin (tuple): GPS origin coordinates for projection.
                name (str): Map name.
                scenario_type (str): Scenario type.
                country (str): Country code.

        Returns:
            Map: A Tactics2D Map populated with all elements parsed from the OSM file.
        """
        xml_root = ET.parse(file_path).getroot()

        if configs is not None:
            project_rule = configs.get("project_rule", None)
            gps_origin = configs.get("gps_origin", None)
        else:
            project_rule = None
            gps_origin = None

        projector = Proj(**project_rule) if project_rule else None
        to_project = None not in [projector, gps_origin]

        if to_project:
            origin = projector(*gps_origin)

        if configs is None:
            map_ = Map()
        else:
            map_ = Map(
                name=configs.get("name"),
                scenario_type=configs.get("scenario_type"),
                country=configs.get("country"),
            )

        node_boundary = xml_root.find("bounds")
        if node_boundary is not None:
            map_.set_boundary(
                self._load_bounds(node_boundary, projector, origin)
                if to_project
                else self._load_bounds_no_proj(node_boundary)
            )

        if to_project:
            for xml_node in xml_root.findall("node"):
                if xml_node.get("action") == "delete":
                    continue
                map_.add_node(self._load_nodes(xml_node, projector, origin))
        else:
            all_nodes = [n for n in xml_root.findall("node") if n.get("action") != "delete"]
            if all_nodes:
                lat0 = float(all_nodes[0].attrib["lat"])
                lon0 = float(all_nodes[0].attrib["lon"])
            else:
                lat0, lon0 = 0.0, 0.0

            for xml_node in all_nodes:
                map_.add_node(self._load_nodes_no_proj(xml_node, lat0, lon0))

        if self.lanelet2:
            for xml_node in xml_root.findall("way"):
                if xml_node.get("action") == "delete":
                    continue
                map_.add_roadline(self._load_roadline_lanelet2(xml_node, map_))

            for xml_node in xml_root.findall("relation"):
                if xml_node.get("action") == "delete":
                    continue
                for tag in xml_node.findall("tag"):
                    if tag.attrib["v"] == "lanelet":
                        map_.add_lane(self._load_lane_lanelet2(xml_node, map_))
                    elif tag.attrib["v"] in ["multipolygon", "area"]:
                        map_.add_area(self._load_area_lanelet2(xml_node, map_))

            for xml_node in xml_root.findall("relation"):
                if xml_node.get("action") == "delete":
                    continue
                for tag in xml_node.findall("tag"):
                    if tag.attrib["v"] == "regulatory_element":
                        map_.add_regulatory(self._load_regulatory_lanelet2(xml_node))

        else:
            for xml_node in xml_root.findall("way"):
                if xml_node.get("action") == "delete":
                    continue
                road_element = self._load_way(xml_node, map_)

                if isinstance(road_element, RoadLine):
                    map_.add_roadline(road_element)
                elif isinstance(road_element, Area):
                    map_.add_area(road_element)

            for xml_node in xml_root.findall("relation"):
                if xml_node.get("action") == "delete":
                    continue
                road_element = self._load_relation(xml_node, map_)

                if isinstance(road_element, RoadLine):
                    map_.add_roadline(road_element)
                elif isinstance(road_element, Area):
                    map_.add_area(road_element)
                elif isinstance(road_element, Regulatory):
                    map_.add_regulatory(road_element)

        return map_
