# Copyright (C) 2026, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""Socket-driven roundabout generator.

Roundabout v1 follows the RoadPort/reference-line workflow:
1. The roundabout module owns the circular ring and fixed circular sockets.
2. Approach curvature is generated by external road modules connected to sockets.
3. Connector lane boundaries are kept virtual to avoid visual petal artefacts.
4. Short visible arm-edge roadlines close the seam with connected road modules.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from shapely.geometry import Polygon

from tactics2d.geometry import (
    curvature_stats,
    has_self_intersection,
    heading_unit,
    normalize_angle,
    offset_polyline,
    polyline_length,
)
from tactics2d.interpolator import Bezier
from tactics2d.map.element import Lane, RoadLine
from tactics2d.map.generator.helpers.element_builder import (
    add_ordered_lane_neighbors,
    build_lane_from_boundaries,
    build_pavement_junction,
    build_roadline_from_points,
)

from ..rules.lane_marking_rules import roundabout_mark, roundabout_mark_kwargs
from ..rules.module_types import RoadModuleResult, RoadPort, make_port


def _bezier_connection(
    p0: np.ndarray, h0: float, p3: np.ndarray, h3: float, step_size: float = 0.1
) -> np.ndarray:
    """Generate a C1-continuous cubic Bezier curve between two poses."""
    p0 = np.asarray(p0, dtype=float)
    p3 = np.asarray(p3, dtype=float)

    chord = float(np.linalg.norm(p3 - p0))
    if chord < 1e-6:
        return np.vstack([p0, p3])

    delta = abs(normalize_angle(h3 - h0))
    tension = 1.0 / 3.0 + (delta / np.pi) * (1.0 / 6.0)
    handle_length = chord * tension

    p1 = p0 + handle_length * heading_unit(h0)
    p2 = p3 - handle_length * heading_unit(h3)

    n = max(2, int(chord / step_size) + 1)
    return Bezier.get_curve(np.array([p0, p1, p2, p3]), n, order=3)


def _arc_points(
    center: np.ndarray,
    radius: float,
    start_angle: float,
    end_angle: float,
    clockwise: bool = True,
    step_size: float = 0.1,
) -> np.ndarray:
    """Sample points along a circular arc."""
    if clockwise:
        delta = (start_angle - end_angle) % (2.0 * np.pi)
    else:
        delta = (end_angle - start_angle) % (2.0 * np.pi)

    if delta < 1e-6:
        delta = 2.0 * np.pi

    n = max(2, int(radius * delta / max(step_size, 1e-6)) + 1)
    t = np.linspace(0.0, delta, n)

    if clockwise:
        angles = start_angle - t
    else:
        angles = start_angle + t

    return center + radius * np.column_stack([np.cos(angles), np.sin(angles)])


def _normalize_arm(
    center: np.ndarray,
    arm: dict[str, Any] | RoadPort,
    default_radius: float,
    default_lane_width: float,
    default_speed_limit: float,
) -> dict[str, Any]:
    """Convert an arm descriptor into a fixed circular roundabout socket.

    Dict arms are projected onto the circular outer boundary. The optional
    curvature field is preserved as metadata only; it does not move the socket.
    Curved approaches should be generated by external road modules.
    """
    if isinstance(arm, RoadPort):
        point = np.asarray(arm.point, dtype=float)
        heading_outward = float(arm.heading)

        return {
            "point": point,
            "heading_outward": heading_outward,
            "heading_inward": heading_outward + np.pi,
            "lane_num": int(arm.lane_num),
            "lane_width": float(arm.lane_width),
            "speed_limit": float(arm.speed_limit),
            "curvature": 0.0,
            "radius": float(np.linalg.norm(point - center)),
        }

    if "heading" not in arm or "lane_num" not in arm:
        raise ValueError("Each arm dict must contain 'heading' and 'lane_num'.")

    heading_outward = float(arm["heading"])
    arm_radius = float(arm.get("radius", default_radius))
    lane_width = float(arm.get("lane_width", default_lane_width))
    point = center + arm_radius * heading_unit(heading_outward)

    return {
        "point": point,
        "heading_outward": heading_outward,
        "heading_inward": heading_outward + np.pi,
        "lane_num": int(arm["lane_num"]),
        "lane_width": lane_width,
        "speed_limit": float(arm.get("speed_limit", default_speed_limit)),
        "curvature": float(arm.get("curvature", 0.0)),
        "radius": arm_radius,
    }


def _roundabout_junction_shape(
    center: np.ndarray, outer_radius: float, step_size: float
) -> list[tuple[float, float]]:
    """Create a circular junction pavement shape."""
    n = max(64, int(2.0 * np.pi * outer_radius / max(step_size, 1e-6)))
    angles = np.linspace(0.0, 2.0 * np.pi, n, endpoint=False)

    pts = [
        (
            float(center[0] + outer_radius * np.cos(angle)),
            float(center[1] + outer_radius * np.sin(angle)),
        )
        for angle in angles
    ]
    pts.append(pts[0])

    return pts


def _virtual_connection_roadline(id_: int, points: np.ndarray, role: str, side: str) -> RoadLine:
    """Create a non-rendered connector boundary RoadLine."""
    return build_roadline_from_points(
        id_=id_,
        points=points,
        type_="virtual",
        subtype="virtual",
        color="white",
        custom_tags={
            "module": "roundabout",
            "role": role,
            "side": side,
            "marking_token": roundabout_mark("connection"),
            "marking_role": "virtual",
        },
    )


def _arm_opening_half_angle(arm: dict[str, Any], outer_ring_radius: float) -> float:
    """Return the circular opening half-angle induced by an arm throat width.

    This stays local to roundabout because the meaning depends on the arm throat
    model used by this module.
    """
    half_width = int(arm["lane_num"]) * float(arm["lane_width"])

    if outer_ring_radius <= 1e-9:
        return np.pi / 8.0

    ratio = float(np.clip(half_width / outer_ring_radius, 1e-6, 0.95))
    return float(np.arcsin(ratio))


def _ray_circle_intersection(
    start: np.ndarray, direction: np.ndarray, center: np.ndarray, radius: float
) -> np.ndarray:
    """Return the first forward intersection of a ray and a circle."""
    start = np.asarray(start, dtype=float)
    direction = np.asarray(direction, dtype=float)
    center = np.asarray(center, dtype=float)

    norm = float(np.linalg.norm(direction))
    if norm < 1e-9:
        return start.copy()

    direction = direction / norm
    p = start - center

    a = float(np.dot(direction, direction))
    b = 2.0 * float(np.dot(p, direction))
    c = float(np.dot(p, p) - radius * radius)

    discriminant = b * b - 4.0 * a * c
    if discriminant < 0.0:
        return start.copy()

    sqrt_discriminant = float(np.sqrt(discriminant))
    t1 = (-b - sqrt_discriminant) / (2.0 * a)
    t2 = (-b + sqrt_discriminant) / (2.0 * a)

    candidates = [t for t in (t1, t2) if t >= 0.0]
    if len(candidates) == 0:
        return start.copy()

    t = min(candidates)
    return start + t * direction


def _arm_outer_edge_roadlines(
    center: np.ndarray, arm: dict[str, Any], arm_idx: int, outer_ring_radius: float, id_counter: int
) -> tuple[list[RoadLine], int]:
    """Create visible short road-edge lines between arm road and roundabout shell.

    These seam-closure lines follow the connected road boundary direction
    instead of diagonally connecting to circular opening endpoints.
    """
    boundary_pt = np.asarray(arm["point"], dtype=float)
    h_in = float(arm["heading_inward"])
    h_out = float(arm["heading_outward"])

    lane_num = int(arm["lane_num"])
    lane_width = float(arm["lane_width"])

    normal = np.array([-np.sin(h_in), np.cos(h_in)], dtype=float)

    positive_edge_start = boundary_pt + lane_num * lane_width * normal
    negative_edge_start = boundary_pt - lane_num * lane_width * normal

    # Move from the arm socket toward the roundabout center along the road axis.
    # For straight four-arm examples this produces vertical/horizontal seam
    # lines, not diagonal chords.
    inward_direction = -heading_unit(h_out)

    positive_edge_end = _ray_circle_intersection(
        start=positive_edge_start,
        direction=inward_direction,
        center=center,
        radius=outer_ring_radius,
    )
    negative_edge_end = _ray_circle_intersection(
        start=negative_edge_start,
        direction=inward_direction,
        center=center,
        radius=outer_ring_radius,
    )

    edge_specs = [
        ("positive_outer_edge", np.vstack([positive_edge_start, positive_edge_end])),
        ("negative_outer_edge", np.vstack([negative_edge_start, negative_edge_end])),
    ]

    roadlines: list[RoadLine] = []

    for role, points in edge_specs:
        if np.linalg.norm(points[-1] - points[0]) < 1e-6:
            continue

        roadline = build_roadline_from_points(
            id_=id_counter,
            points=points,
            marking_kwargs=roundabout_mark_kwargs(
                "ring_outer",
                custom_tags={
                    "module": "roundabout",
                    "role": "arm_outer_edge",
                    "edge_role": role,
                    "arm": arm_idx,
                    "render_width": 0.6,
                },
            ),
        )
        id_counter += 1
        roadlines.append(roadline)

    return roadlines, id_counter


def roundabout(
    center: np.ndarray,
    arms: list[dict[str, Any] | RoadPort],
    ring_radius: float = 15.0,
    ring_lane_num: int = 1,
    lane_width: float = 3.5,
    speed_limit: float = 20.0,
    step_size: float = 0.1,
    id_offset: int = 0,
) -> RoadModuleResult:
    """Generate a roundabout module.

    The roundabout socket is fixed on the circular outer boundary. If an
    approach road should be curved, connect a curved two_way or one_way module
    to the returned interface instead of moving the roundabout socket itself.
    """
    center = np.asarray(center, dtype=float)

    if len(arms) < 2:
        raise ValueError("roundabout requires at least 2 arms.")
    if ring_lane_num < 1:
        raise ValueError("ring_lane_num must be >= 1.")
    if lane_width <= 0.0:
        raise ValueError("lane_width must be positive.")
    if ring_radius <= 0.0:
        raise ValueError("ring_radius must be positive.")
    if step_size <= 0.0:
        raise ValueError("step_size must be positive.")

    outer_ring_radius = ring_radius + ring_lane_num * lane_width
    normalized_arms = [
        _normalize_arm(
            center=center,
            arm=arm,
            default_radius=outer_ring_radius,
            default_lane_width=lane_width,
            default_speed_limit=speed_limit,
        )
        for arm in arms
    ]

    for i, arm in enumerate(normalized_arms):
        if arm["lane_num"] < 1:
            raise ValueError(f"arm[{i}] lane_num must be >= 1.")
        if arm["lane_width"] <= 0.0:
            raise ValueError(f"arm[{i}] lane_width must be positive.")

    n_arms = len(normalized_arms)
    id_counter = id_offset

    lanes: list[Lane] = []
    roadlines: list[RoadLine] = []
    ring_segment_lanes: list[list[Lane]] = []
    connection_centerlines: list[np.ndarray] = []
    ring_centerlines: list[np.ndarray] = []

    sorted_indices = sorted(
        range(n_arms),
        key=lambda idx: normalized_arms[idx]["heading_outward"] % (2.0 * np.pi),
        reverse=True,
    )

    opening_half_angles = [
        _arm_opening_half_angle(arm, outer_ring_radius) for arm in normalized_arms
    ]
    entry_offsets = [0.6 * angle for angle in opening_half_angles]
    exit_offsets = [0.6 * angle for angle in opening_half_angles]

    # Ring lanes between adjacent arm openings.
    for seg_i in range(n_arms):
        curr_idx = sorted_indices[seg_i]
        next_idx = sorted_indices[(seg_i + 1) % n_arms]

        curr_angle = normalized_arms[curr_idx]["heading_outward"] % (2.0 * np.pi)
        next_angle = normalized_arms[next_idx]["heading_outward"] % (2.0 * np.pi)

        # Visible circular ring roadlines stop at the geometric throat opening.
        # The short straight throat edges are generated separately by
        # _arm_outer_edge_roadlines(), so there is no diagonal seam patch.
        seg_start = curr_angle - opening_half_angles[curr_idx]
        seg_end = next_angle + opening_half_angles[next_idx]

        seg_lanes: list[Lane] = []

        for lane_i in range(ring_lane_num):
            inner_radius = ring_radius + lane_i * lane_width
            outer_radius = ring_radius + (lane_i + 1) * lane_width
            center_radius = ring_radius + (lane_i + 0.5) * lane_width

            outer_arc = _arc_points(
                center=center,
                radius=outer_radius,
                start_angle=seg_start,
                end_angle=seg_end,
                clockwise=True,
                step_size=step_size,
            )
            inner_arc = _arc_points(
                center=center,
                radius=inner_radius,
                start_angle=seg_start,
                end_angle=seg_end,
                clockwise=True,
                step_size=step_size,
            )
            center_arc = _arc_points(
                center=center,
                radius=center_radius,
                start_angle=seg_start,
                end_angle=seg_end,
                clockwise=True,
                step_size=step_size,
            )
            ring_centerlines.append(center_arc)

            is_outermost = lane_i == ring_lane_num - 1
            is_innermost = lane_i == 0

            outer_role = "ring_outer" if is_outermost else "ring_interior"
            inner_role = "ring_inner" if is_innermost else "ring_interior"

            outer_roadline = build_roadline_from_points(
                id_=id_counter,
                points=outer_arc,
                marking_kwargs=roundabout_mark_kwargs(
                    outer_role,
                    custom_tags={
                        "segment": seg_i,
                        "ring_lane_index": lane_i,
                        "side": "outer",
                        "render_width": 0.6,
                    },
                ),
            )
            id_counter += 1

            inner_roadline = build_roadline_from_points(
                id_=id_counter,
                points=inner_arc,
                marking_kwargs=roundabout_mark_kwargs(
                    inner_role,
                    custom_tags={
                        "segment": seg_i,
                        "ring_lane_index": lane_i,
                        "side": "inner",
                        "render_width": 0.6,
                    },
                ),
            )
            id_counter += 1

            ring_lane = build_lane_from_boundaries(
                id_=id_counter,
                left_points=outer_arc,
                right_points=inner_arc,
                left_roadline_ids=outer_roadline.id_,
                right_roadline_ids=inner_roadline.id_,
                speed_limit=speed_limit,
                custom_tags={
                    "module": "roundabout",
                    "segment": seg_i,
                    "ring_lane_index": lane_i,
                    "from_arm": curr_idx,
                    "to_arm": next_idx,
                },
            )
            id_counter += 1

            lanes.append(ring_lane)
            roadlines.extend([outer_roadline, inner_roadline])
            seg_lanes.append(ring_lane)

        add_ordered_lane_neighbors(seg_lanes)
        ring_segment_lanes.append(seg_lanes)

    incoming_lane_ids: list[list[str]] = [[] for _ in range(n_arms)]
    outgoing_lane_ids: list[list[str]] = [[] for _ in range(n_arms)]

    # Entry and exit connector lanes. Their boundaries are virtual to avoid
    # flower/petal-looking lane markings inside the roundabout.
    for arm_idx, arm in enumerate(normalized_arms):
        h_in = float(arm["heading_inward"])
        h_out = float(arm["heading_outward"])
        boundary_pt = np.asarray(arm["point"], dtype=float)
        arm_lane_num = int(arm["lane_num"])
        arm_lane_width = float(arm["lane_width"])
        arm_speed = float(arm["speed_limit"])
        pair_num = min(arm_lane_num, ring_lane_num)

        normal = np.array([-np.sin(h_in), np.cos(h_in)], dtype=float)
        arm_angle = h_out % (2.0 * np.pi)

        for lane_i in range(pair_num):
            ring_center_radius = ring_radius + (lane_i + 0.5) * lane_width

            # Entry: outside road -> ring.
            entry_angle = arm_angle + entry_offsets[arm_idx]
            entry_contact = center + ring_center_radius * np.array(
                [np.cos(entry_angle), np.sin(entry_angle)], dtype=float
            )
            entry_heading_clockwise = entry_angle - np.pi / 2.0

            arm_entry_pt = boundary_pt - (lane_i + 0.5) * arm_lane_width * normal
            entry_centerline = _bezier_connection(
                arm_entry_pt, h_in, entry_contact, entry_heading_clockwise, step_size
            )

            entry_left_pts = offset_polyline(entry_centerline, arm_lane_width / 2.0)
            entry_right_pts = offset_polyline(entry_centerline, -arm_lane_width / 2.0)

            entry_left_roadline = _virtual_connection_roadline(
                id_=id_counter, points=entry_left_pts, role="entry_connection_boundary", side="left"
            )
            id_counter += 1

            entry_right_roadline = _virtual_connection_roadline(
                id_=id_counter,
                points=entry_right_pts,
                role="entry_connection_boundary",
                side="right",
            )
            id_counter += 1

            entry_lane = build_lane_from_boundaries(
                id_=id_counter,
                left_points=entry_left_pts,
                right_points=entry_right_pts,
                left_roadline_ids=entry_left_roadline.id_,
                right_roadline_ids=entry_right_roadline.id_,
                speed_limit=min(speed_limit, arm_speed),
                custom_tags={
                    "module": "roundabout",
                    "arm": arm_idx,
                    "type": "entry",
                    "lane_index": lane_i,
                },
            )
            id_counter += 1

            lanes.append(entry_lane)
            roadlines.extend([entry_left_roadline, entry_right_roadline])
            outgoing_lane_ids[arm_idx].append(entry_lane.id_)
            connection_centerlines.append(entry_centerline)

            # Exit: ring -> outside road.
            exit_angle = arm_angle - exit_offsets[arm_idx]
            exit_contact = center + ring_center_radius * np.array(
                [np.cos(exit_angle), np.sin(exit_angle)], dtype=float
            )
            exit_heading_clockwise = exit_angle - np.pi / 2.0

            arm_exit_pt = boundary_pt + (lane_i + 0.5) * arm_lane_width * normal
            exit_centerline = _bezier_connection(
                exit_contact, exit_heading_clockwise, arm_exit_pt, h_out, step_size
            )

            exit_left_pts = offset_polyline(exit_centerline, arm_lane_width / 2.0)
            exit_right_pts = offset_polyline(exit_centerline, -arm_lane_width / 2.0)

            exit_left_roadline = _virtual_connection_roadline(
                id_=id_counter, points=exit_left_pts, role="exit_connection_boundary", side="left"
            )
            id_counter += 1

            exit_right_roadline = _virtual_connection_roadline(
                id_=id_counter, points=exit_right_pts, role="exit_connection_boundary", side="right"
            )
            id_counter += 1

            exit_lane = build_lane_from_boundaries(
                id_=id_counter,
                left_points=exit_left_pts,
                right_points=exit_right_pts,
                left_roadline_ids=exit_left_roadline.id_,
                right_roadline_ids=exit_right_roadline.id_,
                speed_limit=min(speed_limit, arm_speed),
                custom_tags={
                    "module": "roundabout",
                    "arm": arm_idx,
                    "type": "exit",
                    "lane_index": lane_i,
                },
            )
            id_counter += 1

            lanes.append(exit_lane)
            roadlines.extend([exit_left_roadline, exit_right_roadline])
            incoming_lane_ids[arm_idx].append(exit_lane.id_)
            connection_centerlines.append(exit_centerline)

    # Visible seam closure between the approach road rectangle and the
    # roundabout circular shell. These short edge roadlines follow the approach
    # road direction, so four-arm examples get vertical/horizontal seam edges.
    for arm_idx, arm in enumerate(normalized_arms):
        edge_roadlines, id_counter = _arm_outer_edge_roadlines(
            center=center,
            arm=arm,
            arm_idx=arm_idx,
            outer_ring_radius=outer_ring_radius,
            id_counter=id_counter,
        )
        roadlines.extend(edge_roadlines)

    junction_shape = _roundabout_junction_shape(
        center=center, outer_radius=outer_ring_radius, step_size=step_size
    )

    junction = build_pavement_junction(
        id_=id_counter,
        shape_points=junction_shape,
        center=center,
        junction_type="roundabout",
        sumo_type="priority",
        custom_tags={
            "ring_radius": float(ring_radius),
            "outer_ring_radius": float(outer_ring_radius),
            "ring_lane_num": int(ring_lane_num),
        },
    )
    id_counter += 1

    ports: dict[str, RoadPort] = {}
    interfaces: list[dict[str, Any]] = []

    for arm_idx, arm in enumerate(normalized_arms):
        inward_port = RoadPort(
            point=np.asarray(arm["point"], dtype=float),
            heading=float(arm["heading_inward"]),
            lane_num=int(arm["lane_num"]),
            lane_width=float(arm["lane_width"]),
            speed_limit=float(arm["speed_limit"]),
        )
        outward_port = RoadPort(
            point=np.asarray(arm["point"], dtype=float),
            heading=float(arm["heading_outward"]),
            lane_num=int(arm["lane_num"]),
            lane_width=float(arm["lane_width"]),
            speed_limit=float(arm["speed_limit"]),
        )

        ports[f"arm_{arm_idx}_in"] = make_port(
            inward_port,
            kind="roundabout_in",
            name=f"arm_{arm_idx}_in",
            lane_ids=tuple(outgoing_lane_ids[arm_idx]),
            metadata={"module": "roundabout", "arm_index": arm_idx, "direction": "into_roundabout"},
        )
        ports[f"arm_{arm_idx}_out"] = make_port(
            outward_port,
            kind="roundabout_out",
            name=f"arm_{arm_idx}_out",
            lane_ids=tuple(incoming_lane_ids[arm_idx]),
            metadata={
                "module": "roundabout",
                "arm_index": arm_idx,
                "direction": "out_of_roundabout",
            },
        )

        interfaces.append(
            {
                "point": np.asarray(arm["point"], dtype=float),
                "heading": float(arm["heading_outward"]),
                "lane_num": int(arm["lane_num"]),
                "lane_width": float(arm["lane_width"]),
                "speed_limit": float(arm["speed_limit"]),
                "curvature": float(arm["curvature"]),
                "incoming_lane_ids": incoming_lane_ids[arm_idx],
                "outgoing_lane_ids": outgoing_lane_ids[arm_idx],
            }
        )

    all_centerlines = connection_centerlines + ring_centerlines

    max_curvature = 0.0
    max_curvature_rate = 0.0
    total_length = 0.0
    self_intersection = False

    for centerline in all_centerlines:
        stats = curvature_stats(centerline)
        max_curvature = max(max_curvature, stats["max_abs_curvature"])
        max_curvature_rate = max(max_curvature_rate, stats["max_abs_curvature_rate"])
        total_length += polyline_length(centerline)
        self_intersection = self_intersection or has_self_intersection(centerline)

    try:
        junction_area = float(Polygon(junction_shape).area)
    except Exception:
        junction_area = 0.0

    accepted_reasons = []
    if self_intersection:
        accepted_reasons.append("self_intersection")

    quality = {
        "module": "roundabout",
        "arm_num": n_arms,
        "ring_radius": float(ring_radius),
        "outer_ring_radius": float(outer_ring_radius),
        "ring_lane_num": int(ring_lane_num),
        "connection_count": sum(len(ids) for ids in incoming_lane_ids)
        + sum(len(ids) for ids in outgoing_lane_ids),
        "arm_outer_edge_count": int(2 * n_arms),
        "total_length": total_length,
        "self_intersection": self_intersection,
        "max_abs_curvature": max_curvature,
        "max_abs_curvature_rate": max_curvature_rate,
        "junction_area": junction_area,
        "accepted_reasons": accepted_reasons,
        "accepted": len(accepted_reasons) == 0,
    }

    return RoadModuleResult(
        lanes=lanes,
        roadlines=roadlines,
        junctions=[junction],
        ports=ports,
        interfaces=interfaces,
        quality=quality,
        id_counter=id_counter,
    )
