# Copyright (C) 2025, Tactics2D Authors. Released under the GNU GPLv3.
# SPDX-License-Identifier: GPL-3.0-or-later

"""Render configuration implementation."""


COLOR_PALETTE = {
    "red": "#fc5c65",
    "light-red": "#fc5c65",
    "orange": "#fa8231",
    "light-orange": "#fd9644",
    "yellow": "#f7b731",
    "light-yellow": "#fed330",
    "green": "#20bf6b",
    "light-green": "#26de81",
    "turquoise": "#0fb9b1",
    "light-turquoise": "#2bcbba",
    "blue": "#2d98da",
    "light-blue": "#45aaf2",
    "royal-blue": "#3867d6",
    "light-royal-blue": "#4b7bec",
    "purple": "#8854d0",
    "light-purple": "#a55eea",
    "white": "#f1f2f6",
    "light-gray": "#a5b1c2",
    "gray": "#b2bec3",
    "dark-gray": "#4b6584",
    "black": "#2f3542",
}

DEFAULT_COLOR = {
    # default color for lane class subtypes
    "lane": "black",
    "slipLane": "black",
    "road": "black",
    "driving": "black",
    "bidirectional": "black",
    "highway": "black",
    "play_street": "gray",
    "emergency_lane": "red",
    "bus_lane": "dark-gray",
    "bus": "dark-gray",
    "bicycle_lane": "dark-gray",
    "biking": "dark-gray",
    "offRamp": "dark-gray",
    "onRamp": "dark-gray",
    "entry": "green",
    "exit": "green",
    "sidewalk": "gray",
    "walking": "gray",
    "walkway": "gray",
    "shared_walkway": "gray",
    "crosswalk": "dark-gray",
    "stairs": "gray",
    # default color for area class subtypes
    "area": "black",
    "hole": "white",
    "parking": "black",
    "parkingSpace": "black",
    "rail": "dark-gray",
    "freespace": "black",
    "vegetation": "green",
    "keepout": "red",
    "stop": "red",
    "building": "gray",
    "traffic_island": "dark-gray",
    "obstacle": "gray",
    # default color for roadline class subtypes
    "roadline": "white",
    "solid": "white",
    "curbstone": "light-gray",
    "road_border": "light-gray",
    # default color for vehicle class subtypes
    "vehicle": "light-turquoise",
    "car": "light-turquoise",
    "truck": "light-turquoise",
    "bus": "light-turquoise",
    # default color for cyclist class subtypes
    "motorcycle": "light-orange",
    "cyclist": "light-orange",
    "bicycle": "light-orange",
    # default color for pedestrian class subtypes
    "pedestrian": "light-blue",
}

DEFAULT_ORDER = {
    # default zorder for lane class subtypes
    "lane": 3,
    "slipLane": 3,
    "road": 3,
    "driving": 3,
    "bidirectional": 3,
    "highway": 3,
    "play_street": 3,
    "emergency_lane": 3,
    "bus_lane": 2,
    "bus": 2,
    "bicycle_lane": 2,
    "biking": 2,
    "exit": 3,
    "entry": 3,
    "offRamp": 3,
    "onRamp": 3,
    "walkway": 3,
    "shared_walkway": 3,
    "crosswalk": 2,
    "stairs": 3,
    # default zorder for area class subtypes
    "area": 2,
    "hole": 3,
    "parking": 3,
    "parkingSpace": 3,
    "freespace": 3,
    "vegetation": 3,
    "keepout": 3,
    "building": 5,
    "traffic_island": 3,
    "obstacle": 5,
    # default zorder for roadline class subtypes
    "roadline": 4,
    "solid": 4,
    "dashed": 4,
    "road_border": 4,
    "curbstone": 5,
    "vehicle": 6,
    "car": 6,
    "truck": 6,
    "bus": 6,
    "heading_arrow": 7,
    # default zorder for cyclist class subtypes
    "motorcycle": 6,
    "cyclist": 6,
    "bicycle": 6,
    # default zorder for pedestrian class subtypes
    "pedestrian": 6,
}
